import type { ExpenseItem } from '@/types/admin.types';

// ─── Financial Mock Data (12 months: Mar 2025 -> Feb 2026) ───

export const FIN_MONTHS: string[] = [
  '2025-03',
  '2025-04',
  '2025-05',
  '2025-06',
  '2025-07',
  '2025-08',
  '2025-09',
  '2025-10',
  '2025-11',
  '2025-12',
  '2026-01',
  '2026-02',
];

export const FIN_MONTH_LABELS: string[] = [
  'Mar 25',
  'Apr 25',
  'May 25',
  'Jun 25',
  'Jul 25',
  'Aug 25',
  'Sep 25',
  'Oct 25',
  'Nov 25',
  'Dec 25',
  'Jan 26',
  'Feb 26',
];

// ─── Monthly Revenue ─────────────────────────────────────────
export const FIN_REVENUE = [
  { month: '2025-03', subscriptions: 1200, signups: 8, failed: 120, refunds: 0, momoFees: 18, cardFees: 12 },
  { month: '2025-04', subscriptions: 1450, signups: 11, failed: 50, refunds: 50, momoFees: 22, cardFees: 14 },
  { month: '2025-05', subscriptions: 1820, signups: 14, failed: 100, refunds: 0, momoFees: 27, cardFees: 18 },
  { month: '2025-06', subscriptions: 2340, signups: 18, failed: 170, refunds: 120, momoFees: 35, cardFees: 23 },
  { month: '2025-07', subscriptions: 2890, signups: 16, failed: 200, refunds: 0, momoFees: 43, cardFees: 29 },
  { month: '2025-08', subscriptions: 3250, signups: 20, failed: 150, refunds: 50, momoFees: 49, cardFees: 33 },
  { month: '2025-09', subscriptions: 3680, signups: 22, failed: 180, refunds: 0, momoFees: 55, cardFees: 37 },
  { month: '2025-10', subscriptions: 4100, signups: 19, failed: 250, refunds: 100, momoFees: 62, cardFees: 41 },
  { month: '2025-11', subscriptions: 4520, signups: 24, failed: 200, refunds: 0, momoFees: 68, cardFees: 45 },
  { month: '2025-12', subscriptions: 4180, signups: 12, failed: 380, refunds: 150, momoFees: 63, cardFees: 42 },
  { month: '2026-01', subscriptions: 4750, signups: 28, failed: 300, refunds: 50, momoFees: 71, cardFees: 48 },
  { month: '2026-02', subscriptions: 5120, signups: 25, failed: 200, refunds: 0, momoFees: 77, cardFees: 51 },
];

// ─── Monthly Expenses (by category) ─────────────────────────
export const FIN_EXPENSES = [
  {
    month: '2025-03',
    infrastructure: 400,
    paymentFees: 30,
    sms: 60,
    staff: 2000,
    marketing: 200,
    software: 150,
    office: 100,
    compliance: 50,
  },
  {
    month: '2025-04',
    infrastructure: 420,
    paymentFees: 36,
    sms: 65,
    staff: 2000,
    marketing: 250,
    software: 150,
    office: 100,
    compliance: 50,
  },
  {
    month: '2025-05',
    infrastructure: 450,
    paymentFees: 45,
    sms: 70,
    staff: 2000,
    marketing: 300,
    software: 150,
    office: 120,
    compliance: 50,
  },
  {
    month: '2025-06',
    infrastructure: 480,
    paymentFees: 58,
    sms: 80,
    staff: 2500,
    marketing: 350,
    software: 180,
    office: 120,
    compliance: 80,
  },
  {
    month: '2025-07',
    infrastructure: 520,
    paymentFees: 72,
    sms: 85,
    staff: 2500,
    marketing: 400,
    software: 180,
    office: 120,
    compliance: 80,
  },
  {
    month: '2025-08',
    infrastructure: 560,
    paymentFees: 82,
    sms: 95,
    staff: 2500,
    marketing: 350,
    software: 200,
    office: 130,
    compliance: 80,
  },
  {
    month: '2025-09',
    infrastructure: 600,
    paymentFees: 92,
    sms: 100,
    staff: 2500,
    marketing: 300,
    software: 200,
    office: 130,
    compliance: 100,
  },
  {
    month: '2025-10',
    infrastructure: 640,
    paymentFees: 103,
    sms: 110,
    staff: 3000,
    marketing: 450,
    software: 200,
    office: 140,
    compliance: 100,
  },
  {
    month: '2025-11',
    infrastructure: 680,
    paymentFees: 113,
    sms: 115,
    staff: 3000,
    marketing: 500,
    software: 220,
    office: 140,
    compliance: 100,
  },
  {
    month: '2025-12',
    infrastructure: 700,
    paymentFees: 105,
    sms: 90,
    staff: 3000,
    marketing: 200,
    software: 220,
    office: 150,
    compliance: 150,
  },
  {
    month: '2026-01',
    infrastructure: 720,
    paymentFees: 119,
    sms: 125,
    staff: 3000,
    marketing: 600,
    software: 220,
    office: 150,
    compliance: 100,
  },
  {
    month: '2026-02',
    infrastructure: 750,
    paymentFees: 128,
    sms: 130,
    staff: 3000,
    marketing: 550,
    software: 250,
    office: 150,
    compliance: 120,
  },
];

// ─── Expense Category Metadata ───────────────────────────────
export const FIN_EXPENSE_CATEGORIES: Record<string, { label: string; icon: string; color: string; desc: string }> = {
  infrastructure: { label: 'Infrastructure', icon: '☁️', color: '#3B82F6', desc: 'Azure AKS, cloud hosting, CDN' },
  paymentFees: { label: 'Payment Processing', icon: '💳', color: '#8B5CF6', desc: 'MoMo & card transaction fees' },
  sms: { label: 'SMS & Comms', icon: '📱', color: '#06B6D4', desc: 'OTP, notifications, Hubtel' },
  staff: { label: 'Staff & Payroll', icon: '👥', color: '#F59E0B', desc: 'Salaries, benefits, contractors' },
  marketing: { label: 'Marketing', icon: '📢', color: '#EC4899', desc: 'Ads, campaigns, partnerships' },
  software: { label: 'Software Licenses', icon: '🔧', color: '#10B981', desc: 'APIs, tools, third-party SaaS' },
  office: { label: 'Office & Admin', icon: '🏢', color: '#6B7280', desc: 'Rent, utilities, supplies' },
  compliance: { label: 'Tax & Compliance', icon: '📋', color: '#EF4444', desc: 'GRA filings, legal, audits' },
};

// ─── Expense Line Items ──────────────────────────────────────
export const FIN_EXPENSE_DETAIL: ExpenseItem[] = [
  {
    id: 'ex1',
    date: '2026-02-01',
    category: 'infrastructure',
    desc: 'Azure AKS monthly',
    amount: 580,
    vendor: 'Microsoft Azure',
    recurring: true,
    ref: 'AZ-2602-001',
    attachments: [{ id: 'att1', name: 'azure-invoice-feb.pdf', type: 'pdf', size: '245 KB', addedAt: '2026-02-01' }],
  },
  {
    id: 'ex2',
    date: '2026-02-01',
    category: 'infrastructure',
    desc: 'Cloudflare CDN',
    amount: 85,
    vendor: 'Cloudflare',
    recurring: true,
    ref: 'CF-2602-001',
    attachments: [],
  },
  {
    id: 'ex3',
    date: '2026-02-01',
    category: 'infrastructure',
    desc: 'Database backup storage',
    amount: 85,
    vendor: 'Microsoft Azure',
    recurring: true,
    ref: 'AZ-2602-002',
    attachments: [],
  },
  {
    id: 'ex4',
    date: '2026-02-01',
    category: 'staff',
    desc: 'February payroll',
    amount: 3000,
    vendor: 'Payroll',
    recurring: true,
    ref: 'PAY-2602-001',
    attachments: [
      { id: 'att2', name: 'payroll-feb-2026.pdf', type: 'pdf', size: '180 KB', addedAt: '2026-02-01' },
      { id: 'att3', name: 'payslips-summary.pdf', type: 'pdf', size: '320 KB', addedAt: '2026-02-01' },
    ],
  },
  {
    id: 'ex5',
    date: '2026-02-03',
    category: 'marketing',
    desc: 'Google Ads campaign',
    amount: 300,
    vendor: 'Google',
    recurring: false,
    ref: 'GAD-2602-001',
    attachments: [{ id: 'att4', name: 'google-ads-receipt.png', type: 'image', size: '98 KB', addedAt: '2026-02-03' }],
  },
  {
    id: 'ex6',
    date: '2026-02-05',
    category: 'marketing',
    desc: 'Facebook/Meta ads',
    amount: 250,
    vendor: 'Meta',
    recurring: false,
    ref: 'META-2602-001',
    attachments: [{ id: 'att5', name: 'meta-ads-invoice.pdf', type: 'pdf', size: '156 KB', addedAt: '2026-02-05' }],
  },
  {
    id: 'ex7',
    date: '2026-02-01',
    category: 'software',
    desc: 'Hubtel SMS API',
    amount: 130,
    vendor: 'Hubtel',
    recurring: true,
    ref: 'HUB-2602-001',
    attachments: [],
  },
  {
    id: 'ex8',
    date: '2026-02-01',
    category: 'software',
    desc: 'Sentry error monitoring',
    amount: 60,
    vendor: 'Sentry',
    recurring: true,
    ref: 'SEN-2602-001',
    attachments: [],
  },
  {
    id: 'ex9',
    date: '2026-02-01',
    category: 'software',
    desc: 'GitHub Teams',
    amount: 60,
    vendor: 'GitHub',
    recurring: true,
    ref: 'GH-2602-001',
    attachments: [
      { id: 'att6', name: 'github-teams-receipt.png', type: 'image', size: '72 KB', addedAt: '2026-02-01' },
    ],
  },
  {
    id: 'ex10',
    date: '2026-02-10',
    category: 'sms',
    desc: 'OTP SMS credits top-up',
    amount: 130,
    vendor: 'Hubtel',
    recurring: false,
    ref: 'SMS-2602-001',
    attachments: [
      { id: 'att7', name: 'hubtel-topup-receipt.jpg', type: 'image', size: '115 KB', addedAt: '2026-02-10' },
    ],
  },
  {
    id: 'ex11',
    date: '2026-02-01',
    category: 'office',
    desc: 'Office rent (Accra)',
    amount: 120,
    vendor: 'Landlord',
    recurring: true,
    ref: 'OFF-2602-001',
    attachments: [
      { id: 'att8', name: 'rent-receipt-feb.jpg', type: 'image', size: '340 KB', addedAt: '2026-02-01' },
      { id: 'att9', name: 'tenancy-agreement.pdf', type: 'pdf', size: '1.2 MB', addedAt: '2025-03-01' },
    ],
  },
  {
    id: 'ex12',
    date: '2026-02-06',
    category: 'office',
    desc: 'Internet & utilities',
    amount: 30,
    vendor: 'Vodafone Ghana',
    recurring: true,
    ref: 'UTL-2602-001',
    attachments: [],
  },
  {
    id: 'ex13',
    date: '2026-02-08',
    category: 'compliance',
    desc: 'Quarterly GRA provisional tax',
    amount: 80,
    vendor: 'GRA',
    recurring: false,
    ref: 'TAX-2602-Q1',
    attachments: [{ id: 'att10', name: 'gra-provisional-q1.pdf', type: 'pdf', size: '95 KB', addedAt: '2026-02-08' }],
  },
  {
    id: 'ex14',
    date: '2026-02-12',
    category: 'compliance',
    desc: 'Legal retainer fee',
    amount: 40,
    vendor: 'Law Firm',
    recurring: true,
    ref: 'LEG-2602-001',
    attachments: [],
  },
  {
    id: 'ex15',
    date: '2026-02-01',
    category: 'paymentFees',
    desc: 'MTN MoMo merchant fees',
    amount: 77,
    vendor: 'MTN Ghana',
    recurring: true,
    ref: 'MOMO-2602-001',
    attachments: [],
  },
  {
    id: 'ex16',
    date: '2026-02-01',
    category: 'paymentFees',
    desc: 'Card processing fees',
    amount: 51,
    vendor: 'Paystack',
    recurring: true,
    ref: 'PSK-2602-001',
    attachments: [
      { id: 'att11', name: 'paystack-statement-feb.pdf', type: 'pdf', size: '210 KB', addedAt: '2026-02-01' },
    ],
  },
];

// ─── Ghana Tax Rates ─────────────────────────────────────────
export const GH_TAX = {
  corporateRate: 0.25,
  startupRebate: 0.5,
  nhil: 0.025,
  getfl: 0.025,
  covidLevy: 0.01,
  vat: 0.15,
} as const;

// ─── Other Cash Flow Items ───────────────────────────────────
export const FIN_CASHFLOW_OTHER = {
  ownerInvestment: 5000,
  loanRepayment: 0,
  dividends: 0,
  equipmentPurchase: 800,
  devCosts: 1200,
} as const;

// ─── Report Types ────────────────────────────────────────────
export const FIN_REPORT_TYPES = [
  {
    id: 'income',
    title: 'Income Statement',
    icon: '📊',
    desc: 'Revenue, expenses, and net income for the period',
    includes: ['Revenue breakdown by plan', 'Operating expense categories', 'Tax calculations (GRA)'],
    formats: ['Excel', 'CSV', 'PDF'],
  },
  {
    id: 'balance',
    title: 'Balance Sheet',
    icon: '⚖️',
    desc: 'Assets, liabilities, and equity snapshot',
    includes: ['Current & fixed assets', 'Short & long-term liabilities', 'Owner equity & retained earnings'],
    formats: ['Excel', 'CSV', 'PDF'],
  },
  {
    id: 'cashflow',
    title: 'Cash Flow Statement',
    icon: '💧',
    desc: 'Operating, investing, and financing cash flows',
    includes: ['Operating cash flow', 'Investing activities', 'Financing activities'],
    formats: ['Excel', 'CSV', 'PDF'],
  },
  {
    id: 'revenue',
    title: 'Revenue Detail',
    icon: '💰',
    desc: 'Detailed revenue by plan, payment method, and period',
    includes: ['Plan-level revenue breakdown', 'Payment method split (MoMo/Card)', 'Failed & refunded amounts'],
    formats: ['Excel', 'CSV', 'PDF'],
  },
  {
    id: 'tax',
    title: 'Tax Summary',
    icon: '📋',
    desc: 'GRA-compliant tax calculation summary',
    includes: ['Corporate tax with startup rebate', 'NHIL, GETFund, COVID levy', 'Effective tax rate analysis'],
    formats: ['Excel', 'CSV', 'PDF'],
  },
  {
    id: 'subscriptions',
    title: 'Subscription Analytics',
    icon: '📈',
    desc: 'Subscriber growth, churn, and plan transitions',
    includes: ['Monthly active subscribers', 'Churn & conversion rates', 'Plan upgrade/downgrade trends'],
    formats: ['Excel', 'CSV', 'PDF'],
  },
  {
    id: 'expenses',
    title: 'Expense Report',
    icon: '🧾',
    desc: 'Detailed expense breakdown with vendor analysis',
    includes: ['Category-level breakdown', 'Vendor spending analysis', 'Recurring vs. one-time split'],
    formats: ['Excel', 'CSV', 'PDF'],
  },
] as const;

// ─── Scheduled Reports ───────────────────────────────────────
export const FIN_SCHEDULED_REPORTS = [
  {
    id: 'sr1',
    report: 'Income Statement',
    frequency: 'Monthly',
    recipient: 'jude@shopchain.io',
    nextRun: '2026-03-01',
    enabled: true,
  },
  {
    id: 'sr2',
    report: 'Tax Summary',
    frequency: 'Quarterly',
    recipient: 'finance@shopchain.io',
    nextRun: '2026-04-01',
    enabled: true,
  },
  {
    id: 'sr3',
    report: 'Subscription Analytics',
    frequency: 'Weekly',
    recipient: 'jude@shopchain.io',
    nextRun: '2026-02-24',
    enabled: true,
  },
  {
    id: 'sr4',
    report: 'Expense Report',
    frequency: 'Monthly',
    recipient: 'finance@shopchain.io',
    nextRun: '2026-03-01',
    enabled: false,
  },
] as const;
