import type { AdminUser, PaymentMethod, PaymentRecord } from '@/types';
import type { AdminShopRecord, AdminRoleId, AdminRoleDef, AdminTeamMember } from '@/types/admin.types';

// ─── Admin Demo Users ────────────────────────────────────────
export const ADMIN_DEMO_USERS: AdminUser[] = [
  {
    id: 'u1',
    name: 'Jude Appiah',
    email: 'jude@shopchain.com',
    phone: '+233 24 111 2222',
    status: 'active',
    plan: 'max',
    shops: 1,
    branches: 2,
    joined: '2025-06-15',
    lastActive: 'Just now',
    avatar: 'JA',
  },
  {
    id: 'u2',
    name: 'Akua Mensah',
    email: 'akua.m@gmail.com',
    phone: '+233 20 555 6666',
    status: 'active',
    plan: 'basic',
    shops: 2,
    branches: 1,
    joined: '2025-08-22',
    lastActive: '1 hour ago',
    avatar: 'AM',
  },
  {
    id: 'u3',
    name: 'Kweku Asamoah',
    email: 'kweku.a@outlook.com',
    phone: '+233 55 777 8888',
    status: 'active',
    plan: 'free',
    shops: 1,
    branches: 0,
    joined: '2025-10-05',
    lastActive: 'Yesterday',
    avatar: 'KA',
  },
  {
    id: 'u4',
    name: 'Esi Boateng',
    email: 'esi.b@yahoo.com',
    phone: '+233 24 333 4444',
    status: 'deactivated',
    plan: 'basic',
    shops: 1,
    branches: 0,
    joined: '2025-07-18',
    lastActive: '2 weeks ago',
    avatar: 'EB',
  },
  {
    id: 'u5',
    name: 'Kofi Owusu',
    email: 'kofi.o@gmail.com',
    phone: '+233 50 999 0000',
    status: 'active',
    plan: 'max',
    shops: 3,
    branches: 5,
    joined: '2025-05-01',
    lastActive: '3 hours ago',
    avatar: 'KO',
  },
  {
    id: 'u6',
    name: 'Ama Serwaa',
    email: 'ama.s@company.com',
    phone: '+233 27 111 3333',
    status: 'pending',
    plan: 'free',
    shops: 0,
    branches: 0,
    joined: '2026-02-10',
    lastActive: 'Never',
    avatar: 'AS',
  },
  {
    id: 'u7',
    name: 'Yaw Frimpong',
    email: 'yaw.f@gmail.com',
    phone: '+233 20 444 7777',
    status: 'active',
    plan: 'free',
    shops: 1,
    branches: 0,
    joined: '2025-12-01',
    lastActive: '5 hours ago',
    avatar: 'YF',
  },
  {
    id: 'u8',
    name: 'Adwoa Poku',
    email: 'adwoa.p@outlook.com',
    phone: '+233 55 888 2222',
    status: 'active',
    plan: 'basic',
    shops: 2,
    branches: 3,
    joined: '2025-09-14',
    lastActive: 'Today',
    avatar: 'AP',
  },
];

// ─── Admin Demo Shops ────────────────────────────────────────
export const ADMIN_DEMO_SHOPS: AdminShopRecord[] = [
  {
    id: 'as1',
    name: "Kofi's Mini Mart",
    type: 'Retail Store',
    owner: 'Jude Appiah',
    ownerEmail: 'jude@shopchain.com',
    plan: 'max',
    branches: 2,
    team: 5,
    status: 'active',
    created: '2025-06-15',
    icon: '🏪',
  },
  {
    id: 'as2',
    name: 'Akua Fashion House',
    type: 'Retail Store',
    owner: 'Akua Mensah',
    ownerEmail: 'akua.m@gmail.com',
    plan: 'basic',
    branches: 1,
    team: 8,
    status: 'active',
    created: '2025-08-25',
    icon: '👗',
  },
  {
    id: 'as3',
    name: 'Kumasi Wholesale Hub',
    type: 'Wholesale',
    owner: 'Akua Mensah',
    ownerEmail: 'akua.m@gmail.com',
    plan: 'basic',
    branches: 0,
    team: 12,
    status: 'active',
    created: '2025-09-10',
    icon: '🏭',
  },
  {
    id: 'as4',
    name: 'Adabraka Pharmacy',
    type: 'Pharmacy',
    owner: 'Kweku Asamoah',
    ownerEmail: 'kweku.a@outlook.com',
    plan: 'free',
    branches: 0,
    team: 3,
    status: 'active',
    created: '2025-10-08',
    icon: '💊',
  },
  {
    id: 'as5',
    name: 'Osu Coffee Lounge',
    type: 'Restaurant / Bar',
    owner: 'Kofi Owusu',
    ownerEmail: 'kofi.o@gmail.com',
    plan: 'max',
    branches: 3,
    team: 10,
    status: 'active',
    created: '2025-05-05',
    icon: '☕',
  },
  {
    id: 'as6',
    name: 'Esi Electronics',
    type: 'Retail Store',
    owner: 'Esi Boateng',
    ownerEmail: 'esi.b@yahoo.com',
    plan: 'basic',
    branches: 0,
    team: 4,
    status: 'suspended',
    created: '2025-07-20',
    icon: '💻',
  },
];

// ─── Payment Methods (keyed by user ID) ──────────────────────
export const MOCK_PAYMENT_METHODS: Record<string, PaymentMethod[]> = {
  u1: [
    {
      id: 'pm1',
      type: 'momo',
      provider: 'MTN MoMo',
      last4: '2222',
      name: 'Jude Appiah',
      isDefault: true,
      added: '2025-06-15',
      status: 'active',
    },
    {
      id: 'pm2',
      type: 'card',
      provider: 'Visa',
      last4: '8841',
      name: 'Jude Appiah',
      expiry: '09/27',
      isDefault: false,
      added: '2025-08-01',
      status: 'active',
    },
  ],
  u2: [
    {
      id: 'pm3',
      type: 'momo',
      provider: 'Vodafone Cash',
      last4: '6666',
      name: 'Akua Mensah',
      isDefault: true,
      added: '2025-08-22',
      status: 'active',
    },
  ],
  u3: [],
  u4: [
    {
      id: 'pm4',
      type: 'momo',
      provider: 'MTN MoMo',
      last4: '4444',
      name: 'Esi Boateng',
      isDefault: true,
      added: '2025-07-18',
      status: 'expired',
    },
  ],
  u5: [
    {
      id: 'pm5',
      type: 'card',
      provider: 'Mastercard',
      last4: '3109',
      name: 'Kofi Owusu',
      expiry: '12/26',
      isDefault: true,
      added: '2025-05-01',
      status: 'active',
    },
    {
      id: 'pm6',
      type: 'momo',
      provider: 'AirtelTigo Money',
      last4: '0000',
      name: 'Kofi Owusu',
      isDefault: false,
      added: '2025-11-10',
      status: 'active',
    },
    {
      id: 'pm7',
      type: 'card',
      provider: 'Visa',
      last4: '5522',
      name: 'Kofi Owusu',
      expiry: '03/25',
      isDefault: false,
      added: '2025-05-01',
      status: 'expired',
    },
  ],
  u6: [],
  u7: [],
  u8: [
    {
      id: 'pm8',
      type: 'momo',
      provider: 'MTN MoMo',
      last4: '2222',
      name: 'Adwoa Poku',
      isDefault: true,
      added: '2025-09-14',
      status: 'active',
    },
  ],
};

// ─── Payment History (keyed by user ID) ──────────────────────
export const MOCK_PAYMENT_HISTORY: Record<string, PaymentRecord[]> = {
  u1: [
    {
      id: 'tx1',
      date: '2026-02-01',
      amount: 120,
      plan: 'Max',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2602-A1M1',
    },
    {
      id: 'tx2',
      date: '2026-01-01',
      amount: 120,
      plan: 'Max',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2601-A1M1',
    },
    {
      id: 'tx3',
      date: '2025-12-01',
      amount: 120,
      plan: 'Max',
      method: 'Visa •8841',
      status: 'paid',
      txRef: 'TXN-2512-A1V1',
    },
    {
      id: 'tx4',
      date: '2025-11-01',
      amount: 120,
      plan: 'Max',
      method: 'Visa •8841',
      status: 'paid',
      txRef: 'TXN-2511-A1V1',
    },
    {
      id: 'tx5',
      date: '2025-10-01',
      amount: 120,
      plan: 'Max',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2510-A1M1',
    },
    {
      id: 'tx6',
      date: '2025-09-01',
      amount: 120,
      plan: 'Max',
      method: 'MTN MoMo •2222',
      status: 'refunded',
      txRef: 'TXN-2509-A1M1',
      note: 'Billing error — refunded',
    },
    {
      id: 'tx7',
      date: '2025-08-01',
      amount: 80,
      plan: 'Basic → Max',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2508-A1M1',
      note: 'Prorated upgrade',
    },
    {
      id: 'tx8',
      date: '2025-07-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2507-A1M1',
    },
  ],
  u2: [
    {
      id: 'tx9',
      date: '2026-02-01',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'paid',
      txRef: 'TXN-2602-A2V1',
    },
    {
      id: 'tx10',
      date: '2026-01-01',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'paid',
      txRef: 'TXN-2601-A2V1',
    },
    {
      id: 'tx11',
      date: '2025-12-01',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'failed',
      txRef: 'TXN-2512-A2V1',
      note: 'Insufficient funds',
    },
    {
      id: 'tx12',
      date: '2025-12-03',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'paid',
      txRef: 'TXN-2512-A2V2',
      note: 'Retry — successful',
    },
    {
      id: 'tx13',
      date: '2025-11-01',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'paid',
      txRef: 'TXN-2511-A2V1',
    },
  ],
  u3: [],
  u4: [
    {
      id: 'tx14',
      date: '2025-11-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •4444',
      status: 'failed',
      txRef: 'TXN-2511-A4M1',
      note: 'Payment method expired',
    },
    {
      id: 'tx15',
      date: '2025-10-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •4444',
      status: 'paid',
      txRef: 'TXN-2510-A4M1',
    },
    {
      id: 'tx16',
      date: '2025-09-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •4444',
      status: 'paid',
      txRef: 'TXN-2509-A4M1',
    },
  ],
  u5: [
    {
      id: 'tx17',
      date: '2026-02-01',
      amount: 120,
      plan: 'Max',
      method: 'Mastercard •3109',
      status: 'paid',
      txRef: 'TXN-2602-A5C1',
    },
    {
      id: 'tx18',
      date: '2026-01-01',
      amount: 120,
      plan: 'Max',
      method: 'Mastercard •3109',
      status: 'paid',
      txRef: 'TXN-2601-A5C1',
    },
    {
      id: 'tx19',
      date: '2025-12-01',
      amount: 120,
      plan: 'Max',
      method: 'Mastercard •3109',
      status: 'paid',
      txRef: 'TXN-2512-A5C1',
    },
    {
      id: 'tx20',
      date: '2025-11-01',
      amount: 120,
      plan: 'Max',
      method: 'Visa •5522',
      status: 'failed',
      txRef: 'TXN-2511-A5V1',
      note: 'Card expired',
    },
    {
      id: 'tx21',
      date: '2025-11-03',
      amount: 120,
      plan: 'Max',
      method: 'Mastercard •3109',
      status: 'paid',
      txRef: 'TXN-2511-A5C1',
      note: 'Retry with new card',
    },
  ],
  u6: [],
  u7: [],
  u8: [
    {
      id: 'tx22',
      date: '2026-02-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2602-A8M1',
    },
    {
      id: 'tx23',
      date: '2026-01-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2601-A8M1',
    },
    {
      id: 'tx24',
      date: '2025-12-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2512-A8M1',
    },
  ],
};

// ─── Per-User Usage Stats ────────────────────────────────────
export const MOCK_USER_USAGE: Record<string, Record<string, number>> = {
  u1: { shops: 1, branches: 2, team: 5, products: 42, transactions: 2870, storageMB: 1420 },
  u2: { shops: 2, branches: 1, team: 8, products: 310, transactions: 4200, storageMB: 980 },
  u3: { shops: 1, branches: 0, team: 1, products: 48, transactions: 185, storageMB: 62 },
  u4: { shops: 1, branches: 0, team: 3, products: 120, transactions: 0, storageMB: 210 },
  u5: { shops: 3, branches: 5, team: 22, products: 680, transactions: 9800, storageMB: 5400 },
  u6: { shops: 0, branches: 0, team: 0, products: 0, transactions: 0, storageMB: 0 },
  u7: { shops: 1, branches: 0, team: 1, products: 47, transactions: 190, storageMB: 88 },
  u8: { shops: 2, branches: 3, team: 12, products: 480, transactions: 4850, storageMB: 1680 },
};

// ─── Admin Roles & Permissions ───────────────────────────────
export const ADMIN_ROLES: Record<AdminRoleId, AdminRoleDef> = {
  super_admin: {
    label: 'Super Admin',
    color: '#F59E0B',
    icon: '👑',
    desc: 'Full unrestricted access to all systems',
    permissions: {
      manageAdmins: true,
      createSuperAdmin: true,
      manageUsers: true,
      manageShops: true,
      managePlans: true,
      deletePlans: true,
      manageBilling: true,
      viewPayments: true,
      grantExemptions: true,
      manageAnnouncements: true,
      viewAuditLog: true,
      systemSettings: true,
    },
  },
  admin: {
    label: 'Admin',
    color: '#8B5CF6',
    icon: '🛡️',
    desc: 'Full access except Super Admin management and system config',
    permissions: {
      manageAdmins: true,
      createSuperAdmin: false,
      manageUsers: true,
      manageShops: true,
      managePlans: true,
      deletePlans: false,
      manageBilling: true,
      viewPayments: true,
      grantExemptions: true,
      manageAnnouncements: true,
      viewAuditLog: true,
      systemSettings: false,
    },
  },
  billing_manager: {
    label: 'Billing Manager',
    color: '#059669',
    icon: '💰',
    desc: 'Financial operations, subscriptions, and plan management',
    permissions: {
      manageAdmins: false,
      createSuperAdmin: false,
      manageUsers: false,
      manageShops: false,
      managePlans: true,
      deletePlans: false,
      manageBilling: true,
      viewPayments: true,
      grantExemptions: true,
      manageAnnouncements: false,
      viewAuditLog: false,
      systemSettings: false,
    },
  },
  support_agent: {
    label: 'Support Agent',
    color: '#3B82F6',
    icon: '🎧',
    desc: 'User support, account management, and announcements',
    permissions: {
      manageAdmins: false,
      createSuperAdmin: false,
      manageUsers: true,
      manageShops: true,
      managePlans: false,
      deletePlans: false,
      manageBilling: false,
      viewPayments: false,
      grantExemptions: true,
      manageAnnouncements: true,
      viewAuditLog: false,
      systemSettings: false,
    },
  },
  auditor: {
    label: 'Auditor',
    color: '#6B7280',
    icon: '🔍',
    desc: 'Read-only access across all sections for compliance and oversight',
    permissions: {
      manageAdmins: false,
      createSuperAdmin: false,
      manageUsers: false,
      manageShops: false,
      managePlans: false,
      deletePlans: false,
      manageBilling: false,
      viewPayments: true,
      grantExemptions: false,
      manageAnnouncements: false,
      viewAuditLog: true,
      systemSettings: false,
    },
  },
};

// ─── Permission Display Labels ───────────────────────────────
export const PERMISSION_LABELS: Record<string, string> = {
  manageAdmins: 'Manage Admins',
  createSuperAdmin: 'Create Super Admins',
  manageUsers: 'Manage Users',
  manageShops: 'Manage Shops',
  managePlans: 'Manage Plans',
  deletePlans: 'Delete Plans',
  manageBilling: 'Manage Billing',
  viewPayments: 'View Payments',
  grantExemptions: 'Grant Exemptions',
  manageAnnouncements: 'Manage Announcements',
  viewAuditLog: 'View Audit Log',
  systemSettings: 'System Settings',
};

// ─── Admin Team Members ──────────────────────────────────────
export const MOCK_ADMIN_TEAM: AdminTeamMember[] = [
  {
    id: 'adm1',
    name: 'Jude Appiah',
    email: 'admin@shopchain.com',
    phone: '+233 24 111 2222',
    role: 'super_admin',
    avatar: 'JA',
    status: 'active',
    createdBy: 'System',
    createdAt: '2025-01-10',
    lastLogin: '2026-02-12 10:30',
    twoFA: true,
  },
  {
    id: 'adm2',
    name: 'Kwame Asante',
    email: 'kwame.a@shopchain.com',
    phone: '+233 20 888 1111',
    role: 'admin',
    avatar: 'KA',
    status: 'active',
    createdBy: 'Jude Appiah',
    createdAt: '2025-04-15',
    lastLogin: '2026-02-12 08:45',
    twoFA: true,
  },
  {
    id: 'adm3',
    name: 'Efua Mensah',
    email: 'efua.m@shopchain.com',
    phone: '+233 55 222 3333',
    role: 'billing_manager',
    avatar: 'EM',
    status: 'active',
    createdBy: 'Jude Appiah',
    createdAt: '2025-06-20',
    lastLogin: '2026-02-11 16:20',
    twoFA: false,
  },
  {
    id: 'adm4',
    name: 'Yaw Boakye',
    email: 'yaw.b@shopchain.com',
    phone: '+233 50 444 5555',
    role: 'support_agent',
    avatar: 'YB',
    status: 'active',
    createdBy: 'Kwame Asante',
    createdAt: '2025-09-01',
    lastLogin: '2026-02-12 09:15',
    twoFA: true,
  },
  {
    id: 'adm5',
    name: 'Ama Darko',
    email: 'ama.d@shopchain.com',
    phone: '+233 27 666 7777',
    role: 'support_agent',
    avatar: 'AD',
    status: 'suspended',
    createdBy: 'Kwame Asante',
    createdAt: '2025-10-15',
    lastLogin: '2026-01-28 11:00',
    twoFA: false,
  },
  {
    id: 'adm6',
    name: 'Kofi Tetteh',
    email: 'kofi.t@auditservice.gov.gh',
    phone: '+233 24 999 0000',
    role: 'auditor',
    avatar: 'KT',
    status: 'active',
    createdBy: 'Jude Appiah',
    createdAt: '2026-01-05',
    lastLogin: '2026-02-10 14:30',
    twoFA: true,
  },
  {
    id: 'adm7',
    name: 'Abena Osei',
    email: 'abena.o@shopchain.com',
    phone: '+233 55 111 4444',
    role: 'billing_manager',
    avatar: 'AO',
    status: 'invited',
    createdBy: 'Jude Appiah',
    createdAt: '2026-02-10',
    lastLogin: null,
    twoFA: false,
  },
];

// ─── Plan Icon Options ───────────────────────────────────────
export const PLAN_ICON_OPTIONS = [
  { group: 'Plans & Tiers', icons: ['🆓', '💙', '💎', '⭐', '👑', '🏆', '🥇', '🥈', '🥉', '🎯'] },
  { group: 'Business', icons: ['🏪', '🏢', '🏭', '💼', '📊', '💰', '💳', '🏦', '📈', '🤝'] },
  { group: 'Tech & Tools', icons: ['⚡', '🔧', '🛠️', '🔑', '🛡️', '🚀', '💡', '🔒', '📱', '💻'] },
  { group: 'Nature & Objects', icons: ['🌟', '✨', '🔥', '💫', '🌈', '🎁', '🎉', '❤️', '💜', '💚'] },
];
