// ─── Audit & Fraud Investigation Mock Data ───
// Ported from ShopChain wireframe (shopchain-inventory final.jsx lines 12690-12795)

import type {
  AuditCategory,
  AuditCategoryDef,
  RiskLevel,
  RiskLevelDef,
  AuditEvent,
  Investigation,
  Anomaly,
  DetectionRule,
  ForensicLogin,
} from '@/types/admin.types';

// ─── Audit Categories ───
export const AUDIT_CATEGORIES: Record<AuditCategory, AuditCategoryDef> = {
  auth: { label: 'Authentication', icon: '🔐', color: '#3B82F6' },
  financial: { label: 'Financial', icon: '💰', color: '#10B981' },
  data: { label: 'Data', icon: '📝', color: '#F59E0B' },
  admin: { label: 'Admin', icon: '🛡️', color: '#8B5CF6' },
  system: { label: 'System', icon: '⚙️', color: '#6B7280' },
};

// ─── Risk Levels ───
export const AUDIT_RISK_LEVELS: Record<RiskLevel, RiskLevelDef> = {
  low: { label: 'Low', color: '#10B981', min: 0, max: 25 },
  medium: { label: 'Medium', color: '#F59E0B', min: 26, max: 50 },
  high: { label: 'High', color: '#EF4444', min: 51, max: 80 },
  critical: { label: 'Critical', color: '#9333EA', min: 81, max: 100 },
};

// ─── Risk Level Helper ───
export const riskLevel = (score: number): RiskLevel =>
  score > 80 ? 'critical' : score > 50 ? 'high' : score > 25 ? 'medium' : 'low';

// ─── Mock Audit Log (30 events) ───
export const MOCK_AUDIT_LOG: AuditEvent[] = [
  {
    id: 'evt1',
    ts: '2026-02-12 10:30:12',
    actor: 'Jude Mensah',
    actorId: 'adm1',
    role: 'super_admin',
    cat: 'admin',
    action: 'Deactivated user',
    target: 'Esi Boateng (usr3)',
    ip: '41.215.160.12',
    device: 'Chrome/Win11',
    session: 'sess_a1b2c3',
    location: 'Accra, GH',
    risk: 15,
    before: { status: 'active' },
    after: { status: 'suspended' },
    note: 'Account deactivated for non-payment',
  },
  {
    id: 'evt2',
    ts: '2026-02-12 09:15:05',
    actor: 'Akua Sarpong',
    actorId: 'adm3',
    role: 'billing_manager',
    cat: 'financial',
    action: 'Refund issued',
    target: 'Kofi Mensah (usr2) \u2014 \u20B5120',
    ip: '41.215.160.45',
    device: 'Safari/Mac',
    session: 'sess_d4e5f6',
    location: 'Accra, GH',
    risk: 35,
    before: { amount: 120, status: 'paid' },
    after: { amount: 120, status: 'refunded' },
    note: 'Customer complaint \u2014 duplicate charge',
  },
  {
    id: 'evt3',
    ts: '2026-02-12 02:47:33',
    actor: 'Kwame Asante',
    actorId: 'adm2',
    role: 'admin',
    cat: 'admin',
    action: 'Exported user data',
    target: 'All users (330 records)',
    ip: '41.215.161.88',
    device: 'Chrome/Win11',
    session: 'sess_g7h8i9',
    location: 'Accra, GH',
    risk: 72,
    before: null,
    after: { records: 330, format: 'CSV' },
    note: 'Off-hours export \u2014 flagged for review',
  },
  {
    id: 'evt4',
    ts: '2026-02-11 22:14:08',
    actor: 'Unknown',
    actorId: null,
    role: null,
    cat: 'auth',
    action: 'Failed login attempt',
    target: 'admin@shopchain.com',
    ip: '105.112.45.67',
    device: 'Firefox/Linux',
    session: null,
    location: 'Lagos, NG',
    risk: 65,
    before: null,
    after: { attempt: 1, reason: 'Invalid password' },
    note: '',
  },
  {
    id: 'evt5',
    ts: '2026-02-11 22:14:32',
    actor: 'Unknown',
    actorId: null,
    role: null,
    cat: 'auth',
    action: 'Failed login attempt',
    target: 'admin@shopchain.com',
    ip: '105.112.45.67',
    device: 'Firefox/Linux',
    session: null,
    location: 'Lagos, NG',
    risk: 70,
    before: null,
    after: { attempt: 2, reason: 'Invalid password' },
    note: '',
  },
  {
    id: 'evt6',
    ts: '2026-02-11 22:14:55',
    actor: 'Unknown',
    actorId: null,
    role: null,
    cat: 'auth',
    action: 'Failed login attempt',
    target: 'admin@shopchain.com',
    ip: '105.112.45.67',
    device: 'Firefox/Linux',
    session: null,
    location: 'Lagos, NG',
    risk: 75,
    before: null,
    after: { attempt: 3, reason: 'Invalid password' },
    note: '',
  },
  {
    id: 'evt7',
    ts: '2026-02-11 22:15:18',
    actor: 'Unknown',
    actorId: null,
    role: null,
    cat: 'auth',
    action: 'Failed login attempt',
    target: 'admin@shopchain.com',
    ip: '105.112.45.67',
    device: 'Firefox/Linux',
    session: null,
    location: 'Lagos, NG',
    risk: 80,
    before: null,
    after: { attempt: 4, reason: 'Invalid password' },
    note: '',
  },
  {
    id: 'evt8',
    ts: '2026-02-11 22:15:40',
    actor: 'Unknown',
    actorId: null,
    role: null,
    cat: 'auth',
    action: 'Failed login attempt',
    target: 'admin@shopchain.com',
    ip: '105.112.45.67',
    device: 'Firefox/Linux',
    session: null,
    location: 'Lagos, NG',
    risk: 88,
    before: null,
    after: { attempt: 5, reason: 'Account locked' },
    note: '5th failed attempt \u2014 auto-lock triggered',
  },
  {
    id: 'evt9',
    ts: '2026-02-11 14:15:00',
    actor: 'Jude Mensah',
    actorId: 'adm1',
    role: 'super_admin',
    cat: 'data',
    action: 'Suspended shop',
    target: 'Esi Electronics (shp_003)',
    ip: '41.215.160.12',
    device: 'Chrome/Win11',
    session: 'sess_j1k2l3',
    location: 'Accra, GH',
    risk: 12,
    before: { status: 'active' },
    after: { status: 'suspended' },
    note: 'Owner account inactive',
  },
  {
    id: 'evt10',
    ts: '2026-02-11 11:32:18',
    actor: 'Ama Owusu',
    actorId: 'usr5',
    role: 'user',
    cat: 'financial',
    action: 'Payment made',
    target: 'Enterprise plan \u2014 \u20B5120',
    ip: '41.215.165.90',
    device: 'Chrome/Android',
    session: 'sess_m4n5o6',
    location: 'Kumasi, GH',
    risk: 5,
    before: null,
    after: { plan: 'Enterprise', amount: 120, method: 'MTN MoMo' },
    note: '',
  },
  {
    id: 'evt11',
    ts: '2026-02-10 16:22:55',
    actor: 'Kofi Mensah',
    actorId: 'usr2',
    role: 'user',
    cat: 'financial',
    action: 'Refund requested',
    target: 'Growth plan \u2014 \u20B549',
    ip: '41.215.162.33',
    device: 'Safari/iPhone',
    session: 'sess_p7q8r9',
    location: 'Accra, GH',
    risk: 40,
    before: null,
    after: { amount: 49, reason: 'Service issue' },
    note: '2nd refund in 5 days',
  },
  {
    id: 'evt12',
    ts: '2026-02-10 09:00:00',
    actor: 'Jude Mensah',
    actorId: 'adm1',
    role: 'super_admin',
    cat: 'admin',
    action: 'Published announcement',
    target: 'New Feature: Branch Management',
    ip: '41.215.160.12',
    device: 'Chrome/Win11',
    session: 'sess_s1t2u3',
    location: 'Accra, GH',
    risk: 5,
    before: null,
    after: { type: 'feature', audience: 'all' },
    note: '',
  },
  {
    id: 'evt13',
    ts: '2026-02-09 15:30:44',
    actor: 'Akua Sarpong',
    actorId: 'adm3',
    role: 'billing_manager',
    cat: 'financial',
    action: 'Refund issued',
    target: 'Kofi Mensah (usr2) \u2014 \u20B549',
    ip: '41.215.160.45',
    device: 'Safari/Mac',
    session: 'sess_v4w5x6',
    location: 'Accra, GH',
    risk: 55,
    before: { amount: 49, status: 'paid' },
    after: { amount: 49, status: 'refunded' },
    note: '2nd refund to same user \u2014 flagged',
  },
  {
    id: 'evt14',
    ts: '2026-02-09 14:10:22',
    actor: 'Pharmacist Adu',
    actorId: 'usr7',
    role: 'user',
    cat: 'data',
    action: 'Inventory adjusted',
    target: 'Accra Pharmacy \u2014 Paracetamol (\u2212200 units)',
    ip: '41.215.168.14',
    device: 'Chrome/Win10',
    session: 'sess_y7z8a1',
    location: 'Accra, GH',
    risk: 78,
    before: { stock: 450 },
    after: { stock: 250, adjustment: -200, reason: 'Manual correction' },
    note: 'Large negative adjustment \u2014 no linked PO or sale',
  },
  {
    id: 'evt15',
    ts: '2026-02-08 16:45:00',
    actor: 'Jude Mensah',
    actorId: 'adm1',
    role: 'super_admin',
    cat: 'admin',
    action: 'Reactivated user',
    target: 'Kweku Asamoah (usr4)',
    ip: '41.215.160.12',
    device: 'Chrome/Win11',
    session: 'sess_b2c3d4',
    location: 'Accra, GH',
    risk: 10,
    before: { status: 'suspended' },
    after: { status: 'active' },
    note: 'Payment issue resolved',
  },
  {
    id: 'evt16',
    ts: '2026-02-08 10:05:33',
    actor: 'Kofi Mensah',
    actorId: 'usr2',
    role: 'user',
    cat: 'financial',
    action: 'Refund requested',
    target: 'Growth plan \u2014 \u20B549',
    ip: '41.215.162.33',
    device: 'Safari/iPhone',
    session: 'sess_e5f6g7',
    location: 'Accra, GH',
    risk: 30,
    before: null,
    after: { amount: 49, reason: 'Accidental charge' },
    note: '1st refund request',
  },
  {
    id: 'evt17',
    ts: '2026-02-07 19:55:10',
    actor: 'Yaw Boakye',
    actorId: 'usr6',
    role: 'user',
    cat: 'auth',
    action: 'Password reset',
    target: 'yaw.b@email.com',
    ip: '41.215.170.22',
    device: 'Chrome/Android',
    session: 'sess_h8i9j1',
    location: 'Takoradi, GH',
    risk: 20,
    before: null,
    after: { method: 'email_link' },
    note: '',
  },
  {
    id: 'evt18',
    ts: '2026-02-07 11:20:00',
    actor: 'Jude Mensah',
    actorId: 'adm1',
    role: 'super_admin',
    cat: 'data',
    action: 'Deleted shop',
    target: 'Test Shop XYZ',
    ip: '41.215.160.12',
    device: 'Chrome/Win11',
    session: 'sess_k2l3m4',
    location: 'Accra, GH',
    risk: 18,
    before: { name: 'Test Shop XYZ' },
    after: null,
    note: 'Owner requested deletion',
  },
  {
    id: 'evt19',
    ts: '2026-02-06 08:30:00',
    actor: 'Esi Boateng',
    actorId: 'usr3',
    role: 'user',
    cat: 'auth',
    action: 'Login',
    target: 'esi.b@email.com',
    ip: '41.215.163.55',
    device: 'Chrome/Android',
    session: 'sess_n5o6p7',
    location: 'Cape Coast, GH',
    risk: 5,
    before: null,
    after: null,
    note: '',
  },
  {
    id: 'evt20',
    ts: '2026-02-05 14:22:18',
    actor: 'Kwame Asante',
    actorId: 'adm2',
    role: 'admin',
    cat: 'admin',
    action: 'Role changed',
    target: 'Akua Sarpong (adm3)',
    ip: '41.215.161.88',
    device: 'Chrome/Win11',
    session: 'sess_q8r9s1',
    location: 'Accra, GH',
    risk: 45,
    before: { role: 'support_agent' },
    after: { role: 'billing_manager' },
    note: 'Promoted to billing manager',
  },
  {
    id: 'evt21',
    ts: '2026-02-05 09:10:44',
    actor: 'Akosua Dankwa',
    actorId: 'usr1',
    role: 'user',
    cat: 'financial',
    action: 'Subscription upgrade',
    target: 'Starter \u2192 Growth',
    ip: '41.215.164.78',
    device: 'Safari/Mac',
    session: 'sess_t2u3v4',
    location: 'Accra, GH',
    risk: 5,
    before: { plan: 'Starter' },
    after: { plan: 'Growth' },
    note: '',
  },
  {
    id: 'evt22',
    ts: '2026-02-04 23:48:12',
    actor: 'Unknown',
    actorId: null,
    role: null,
    cat: 'auth',
    action: 'Failed login attempt',
    target: 'kwame@shopchain.com',
    ip: '196.216.88.120',
    device: 'Chrome/Linux',
    session: null,
    location: 'Nairobi, KE',
    risk: 60,
    before: null,
    after: { attempt: 1, reason: 'Invalid password' },
    note: 'Unusual origin \u2014 Kenya',
  },
  {
    id: 'evt23',
    ts: '2026-02-03 16:05:00',
    actor: 'Kofi Mensah',
    actorId: 'usr2',
    role: 'user',
    cat: 'data',
    action: 'Payment method added',
    target: 'Visa ending 6411',
    ip: '41.215.162.33',
    device: 'Safari/iPhone',
    session: 'sess_w5x6y7',
    location: 'Accra, GH',
    risk: 10,
    before: null,
    after: { method: 'Visa', last4: '6411' },
    note: '',
  },
  {
    id: 'evt24',
    ts: '2026-02-02 10:15:33',
    actor: 'System',
    actorId: 'system',
    role: 'system',
    cat: 'system',
    action: 'Bulk payment retry',
    target: '12 failed payments',
    ip: 'internal',
    device: 'System/Cron',
    session: 'sys_batch',
    location: 'Server',
    risk: 8,
    before: { failed: 12 },
    after: { recovered: 9, stillFailed: 3 },
    note: 'Automated retry cycle',
  },
  {
    id: 'evt25',
    ts: '2026-02-01 12:00:00',
    actor: 'Jude Mensah',
    actorId: 'adm1',
    role: 'super_admin',
    cat: 'admin',
    action: 'Plan pricing updated',
    target: 'Growth plan: \u20B545 \u2192 \u20B549',
    ip: '41.215.160.12',
    device: 'Chrome/Win11',
    session: 'sess_z8a9b1',
    location: 'Accra, GH',
    risk: 30,
    before: { price: 45 },
    after: { price: 49 },
    note: 'Quarterly price adjustment',
  },
  {
    id: 'evt26',
    ts: '2026-01-28 13:30:00',
    actor: 'Akua Sarpong',
    actorId: 'adm3',
    role: 'billing_manager',
    cat: 'financial',
    action: 'Exemption granted',
    target: 'Kweku Asamoah (usr4) \u2014 3 months free',
    ip: '41.215.160.45',
    device: 'Safari/Mac',
    session: 'sess_c2d3e4',
    location: 'Accra, GH',
    risk: 40,
    before: null,
    after: { duration: '3 months', plan: 'Enterprise' },
    note: 'Beta tester reward',
  },
  {
    id: 'evt27',
    ts: '2026-01-25 09:45:00',
    actor: 'System',
    actorId: 'system',
    role: 'system',
    cat: 'system',
    action: 'Webhook triggered',
    target: 'Payment gateway callback',
    ip: 'internal',
    device: 'System',
    session: 'sys_webhook',
    location: 'Server',
    risk: 3,
    before: null,
    after: { event: 'payment.success', txns: 8 },
    note: '',
  },
  {
    id: 'evt28',
    ts: '2026-01-20 15:20:00',
    actor: 'Yaw Boakye',
    actorId: 'usr6',
    role: 'user',
    cat: 'data',
    action: 'Shop created',
    target: 'Takoradi Fresh Produce',
    ip: '41.215.170.22',
    device: 'Chrome/Android',
    session: 'sess_f5g6h7',
    location: 'Takoradi, GH',
    risk: 5,
    before: null,
    after: { name: 'Takoradi Fresh Produce', type: 'Retail' },
    note: '',
  },
  {
    id: 'evt29',
    ts: '2026-01-15 11:00:00',
    actor: 'Pharmacist Adu',
    actorId: 'usr7',
    role: 'user',
    cat: 'auth',
    action: '2FA enabled',
    target: 'pharmacist.adu@email.com',
    ip: '41.215.168.14',
    device: 'Chrome/Win10',
    session: 'sess_i8j9k1',
    location: 'Accra, GH',
    risk: 5,
    before: { twoFA: false },
    after: { twoFA: true },
    note: '',
  },
  {
    id: 'evt30',
    ts: '2026-01-12 08:22:00',
    actor: 'Akosua Dankwa',
    actorId: 'usr1',
    role: 'user',
    cat: 'financial',
    action: 'Payment failed',
    target: 'Starter plan \u2014 \u20B529',
    ip: '41.215.164.78',
    device: 'Safari/Mac',
    session: 'sess_l2m3n4',
    location: 'Accra, GH',
    risk: 15,
    before: null,
    after: { reason: 'Insufficient funds', method: 'MTN MoMo' },
    note: '',
  },
];

// ─── Mock Investigations (4 cases) ───
export const MOCK_INVESTIGATIONS: Investigation[] = [
  {
    id: 'INV-2026-001',
    title: 'Suspicious Refund Pattern (Kofi Mensah)',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Jude Mensah',
    created: '2026-02-10',
    updated: '2026-02-12',
    desc: 'Multiple refunds processed for user Kofi Mensah (usr2) within 5 days totaling \u20B5218. Pattern exceeds normal refund thresholds and warrants investigation into possible abuse of refund policy.',
    linkedEvents: ['evt2', 'evt11', 'evt13', 'evt16', 'evt23'],
    linkedUsers: ['usr2'],
    impact: '\u20B5218',
    notes: [
      {
        id: 'n1',
        author: 'Jude Mensah',
        time: '2026-02-10 16:40',
        text: 'Opened case after 2nd refund flagged by anomaly detection. Reviewing full transaction history.',
      },
      {
        id: 'n2',
        author: 'Akua Sarpong',
        time: '2026-02-11 10:20',
        text: "Confirmed 3 refund requests in 5 days. First was legitimate duplicate charge, 2nd and 3rd cite 'service issues' without specifics.",
      },
      {
        id: 'n3',
        author: 'Jude Mensah',
        time: '2026-02-12 09:30',
        text: 'User also added a new card (Visa 6411) on Feb 3. Checking if payment method change is related to refund pattern.',
      },
    ],
    findings: '',
    resolution: null,
  },
  {
    id: 'INV-2026-002',
    title: 'Unauthorized Admin Access Attempt',
    status: 'open',
    priority: 'critical',
    assignee: 'Kwame Asante',
    created: '2026-02-12',
    updated: '2026-02-12',
    desc: '5 consecutive failed login attempts on admin portal from IP 105.112.45.67 (Lagos, Nigeria) within 90 seconds targeting admin@shopchain.com. Account was auto-locked after 5th attempt.',
    linkedEvents: ['evt4', 'evt5', 'evt6', 'evt7', 'evt8'],
    linkedUsers: [],
    impact: 'Potential',
    notes: [
      {
        id: 'n4',
        author: 'System',
        time: '2026-02-11 22:16',
        text: 'Auto-generated: 5 failed login attempts detected from Lagos IP. Account locked.',
      },
      {
        id: 'n5',
        author: 'Kwame Asante',
        time: '2026-02-12 08:00',
        text: 'IP 105.112.45.67 traced to a commercial ISP in Lagos. No known association with any team member.',
      },
    ],
    findings: '',
    resolution: null,
  },
  {
    id: 'INV-2026-003',
    title: 'Inventory Ghost Adjustment',
    status: 'closed',
    priority: 'medium',
    assignee: 'Jude Mensah',
    created: '2026-02-09',
    updated: '2026-02-11',
    desc: 'Large negative inventory adjustment of 200 units (Paracetamol) at Accra Pharmacy with no corresponding sale, transfer, or purchase order.',
    linkedEvents: ['evt14'],
    linkedUsers: ['usr7'],
    impact: '\u20B51,200 (est.)',
    notes: [
      {
        id: 'n6',
        author: 'Jude Mensah',
        time: '2026-02-09 16:00',
        text: 'Opened case. 200 unit reduction without supporting documentation is unusual.',
      },
      {
        id: 'n7',
        author: 'Jude Mensah',
        time: '2026-02-10 14:30',
        text: 'Contacted Pharmacist Adu. Claims new staff member entered wrong quantity during stocktake.',
      },
      {
        id: 'n8',
        author: 'Jude Mensah',
        time: '2026-02-11 10:00',
        text: 'Verified: physical stock matches corrected count. Error was in initial data entry, not a removal. Closing case.',
      },
    ],
    findings: 'Data entry error by newly onboarded staff during physical stocktake. No fraud detected.',
    resolution: 'no_fraud',
  },
  {
    id: 'INV-2026-004',
    title: 'Duplicate Payment Investigation',
    status: 'escalated',
    priority: 'high',
    assignee: 'Akua Sarpong',
    created: '2026-02-08',
    updated: '2026-02-12',
    desc: 'User Akosua Dankwa (usr1) charged twice for Growth plan subscription renewal via MTN MoMo. Both transactions received confirmation from payment provider.',
    linkedEvents: ['evt21', 'evt30'],
    linkedUsers: ['usr1'],
    impact: '\u20B549',
    notes: [
      {
        id: 'n9',
        author: 'Akua Sarpong',
        time: '2026-02-08 11:00',
        text: 'User reported duplicate charge. Confirmed 2 successful MoMo debits for same subscription period.',
      },
      {
        id: 'n10',
        author: 'Akua Sarpong',
        time: '2026-02-10 09:00',
        text: 'Escalated to Paystack support. Awaiting transaction reconciliation report.',
      },
      {
        id: 'n11',
        author: 'Jude Mensah',
        time: '2026-02-12 08:00',
        text: 'Paystack confirmed gateway timeout caused retry that was charged twice. Refund in progress from their end.',
      },
    ],
    findings: 'Payment gateway timeout caused double charge. Not user or platform error.',
    resolution: null,
  },
];

// ─── Mock Anomalies (8 detected) ───
export const MOCK_ANOMALIES: Anomaly[] = [
  {
    id: 'anom1',
    rule: 'Multiple Failed Logins',
    severity: 'critical',
    entity: 'admin@shopchain.com',
    ts: '2026-02-11 22:15',
    summary: '5 failed login attempts from Lagos IP (105.112.45.67) within 90 seconds',
    status: 'escalated',
    linkedCase: 'INV-2026-002',
    events: ['evt4', 'evt5', 'evt6', 'evt7', 'evt8'],
  },
  {
    id: 'anom2',
    rule: 'Off-Hours Admin Activity',
    severity: 'high',
    entity: 'Kwame Asante (adm2)',
    ts: '2026-02-12 02:47',
    summary: 'Admin exported 330 user records at 2:47 AM via CSV download',
    status: 'reviewing',
    linkedCase: null,
    events: ['evt3'],
  },
  {
    id: 'anom3',
    rule: 'Unusual Refund Pattern',
    severity: 'high',
    entity: 'Kofi Mensah (usr2)',
    ts: '2026-02-10 16:22',
    summary: '3 refund requests within 5 days totaling \u20B5218',
    status: 'escalated',
    linkedCase: 'INV-2026-001',
    events: ['evt11', 'evt13', 'evt16'],
  },
  {
    id: 'anom4',
    rule: 'Large Inventory Adjustment',
    severity: 'high',
    entity: 'Accra Pharmacy (shp_007)',
    ts: '2026-02-09 14:10',
    summary: '\u2212200 units of Paracetamol with no linked PO, sale, or transfer',
    status: 'resolved',
    linkedCase: 'INV-2026-003',
    events: ['evt14'],
  },
  {
    id: 'anom5',
    rule: 'Geographic Anomaly',
    severity: 'medium',
    entity: 'kwame@shopchain.com',
    ts: '2026-02-04 23:48',
    summary: 'Login attempt from Nairobi, Kenya \u2014 user typically logs in from Accra',
    status: 'dismissed',
    linkedCase: null,
    events: ['evt22'],
  },
  {
    id: 'anom6',
    rule: 'Privilege Escalation',
    severity: 'medium',
    entity: 'Akua Sarpong (adm3)',
    ts: '2026-02-05 14:22',
    summary: 'Role upgraded from support_agent to billing_manager, followed by financial operations',
    status: 'dismissed',
    linkedCase: null,
    events: ['evt20'],
  },
  {
    id: 'anom7',
    rule: 'Off-Hours Admin Activity',
    severity: 'low',
    entity: 'Jude Mensah (adm1)',
    ts: '2026-01-30 23:15',
    summary: 'Admin login at 11:15 PM \u2014 reviewed dashboard only, no changes made',
    status: 'dismissed',
    linkedCase: null,
    events: [],
  },
  {
    id: 'anom8',
    rule: 'Bulk Data Export',
    severity: 'medium',
    entity: 'System (sys_batch)',
    ts: '2026-02-02 10:15',
    summary: 'Automated bulk payment retry processed 12 transactions',
    status: 'resolved',
    linkedCase: null,
    events: ['evt24'],
  },
];

// ─── Detection Rules (8 configurable) ───
export const AUDIT_DETECTION_RULES: DetectionRule[] = [
  {
    id: 'dr1',
    name: 'Multiple Failed Logins',
    desc: '>5 failed attempts within 15 minutes from same IP',
    threshold: '5 attempts / 15 min',
    severity: 'critical',
    enabled: true,
    triggers: 2,
  },
  {
    id: 'dr2',
    name: 'Off-Hours Admin Activity',
    desc: 'Admin actions between 11PM\u20135AM local time',
    threshold: '11PM\u20135AM',
    severity: 'high',
    enabled: true,
    triggers: 3,
  },
  {
    id: 'dr3',
    name: 'Unusual Refund Pattern',
    desc: '>3 refunds to same user within 7 days or single refund >\u20B5500',
    threshold: '3 refunds / 7d or >\u20B5500',
    severity: 'high',
    enabled: true,
    triggers: 1,
  },
  {
    id: 'dr4',
    name: 'Large Inventory Adjustment',
    desc: 'Stock adjustment >50 units without linked PO or transfer',
    threshold: '>50 units',
    severity: 'high',
    enabled: true,
    triggers: 1,
  },
  {
    id: 'dr5',
    name: 'Account Takeover Signal',
    desc: 'Password reset + profile change + payment method change within 1 hour',
    threshold: '3 events / 1h',
    severity: 'critical',
    enabled: true,
    triggers: 0,
  },
  {
    id: 'dr6',
    name: 'Geographic Anomaly',
    desc: 'Login from new country within 4 hours of previous session',
    threshold: '4h window',
    severity: 'medium',
    enabled: true,
    triggers: 1,
  },
  {
    id: 'dr7',
    name: 'Privilege Escalation',
    desc: 'Role/permission change followed by high-value action',
    threshold: 'Role change + action',
    severity: 'medium',
    enabled: true,
    triggers: 1,
  },
  {
    id: 'dr8',
    name: 'Bulk Data Export',
    desc: 'Export of >500 records in a single session',
    threshold: '>500 records',
    severity: 'medium',
    enabled: false,
    triggers: 1,
  },
];

// ─── User Forensic Logins (10 records) ───
export const MOCK_USER_FORENSIC_LOGINS: ForensicLogin[] = [
  { ts: '2026-02-12 08:15', ip: '41.215.162.33', device: 'Safari/iPhone', location: 'Accra, GH', status: 'success' },
  { ts: '2026-02-11 09:05', ip: '41.215.162.33', device: 'Safari/iPhone', location: 'Accra, GH', status: 'success' },
  { ts: '2026-02-10 07:52', ip: '41.215.162.33', device: 'Safari/iPhone', location: 'Accra, GH', status: 'success' },
  { ts: '2026-02-09 08:30', ip: '41.215.162.33', device: 'Safari/iPhone', location: 'Accra, GH', status: 'success' },
  { ts: '2026-02-08 10:15', ip: '41.215.162.33', device: 'Chrome/Win10', location: 'Accra, GH', status: 'success' },
  { ts: '2026-02-07 08:00', ip: '41.215.162.33', device: 'Safari/iPhone', location: 'Accra, GH', status: 'success' },
  { ts: '2026-02-05 19:30', ip: '105.112.90.44', device: 'Chrome/Android', location: 'Lagos, NG', status: 'success' },
  { ts: '2026-02-04 08:45', ip: '41.215.162.33', device: 'Safari/iPhone', location: 'Accra, GH', status: 'success' },
  { ts: '2026-02-03 07:55', ip: '41.215.162.33', device: 'Safari/iPhone', location: 'Accra, GH', status: 'failed' },
  { ts: '2026-02-03 07:56', ip: '41.215.162.33', device: 'Safari/iPhone', location: 'Accra, GH', status: 'success' },
];

// ─── Behavioral Flags for Forensic Users ───
export const MOCK_BEHAVIORAL_FLAGS: Record<string, string[]> = {
  usr1: ['New payment method'],
  usr2: ['Multiple refunds', 'New payment method', 'High-risk event'],
  usr3: ['Account deactivated'],
  usr4: ['Recent reactivation'],
  usr5: [],
  usr6: ['Password reset', 'New location login'],
  usr7: ['Large inventory adjustment', 'High-risk event'],
  usr8: [],
};

export const FLAG_COLORS: Record<string, string> = {
  'Multiple refunds': '#EF4444',
  'New payment method': '#F59E0B',
  'High-risk event': '#EF4444',
  'Account deactivated': '#EF4444',
  'Recent reactivation': '#3B82F6',
  'Password reset': '#F59E0B',
  'New location login': '#F59E0B',
  'Large inventory adjustment': '#EF4444',
  'Expired payment method': '#6B7280',
};

// ─── Activity Heatmap: [day(0=Mon)][hour] = count ───
export const MOCK_HEATMAP: number[][] = [
  [0, 0, 0, 0, 0, 0, 0, 1, 4, 5, 6, 4, 3, 4, 5, 4, 3, 2, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 2, 5, 6, 5, 5, 4, 5, 4, 5, 4, 2, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 3, 5, 4, 3, 3, 4, 5, 4, 3, 1, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 2, 4, 5, 5, 4, 4, 5, 6, 5, 4, 2, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 3, 4, 4, 3, 3, 3, 4, 3, 2, 1, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
];
