import type {
  Product,
  Supplier,
  StockAdjustment,
  StockTransfer,
  Customer,
  PurchaseOrder,
  AdminUser,
  AdminShop,
  Session,
  BillingRecord,
  UsageData,
  PaymentMethod,
  PaymentRecord,
  Category,
  UnitOfMeasure,
  SaleRecord,
} from '@/types';
import type { Warehouse } from '@/types/shop.types';
import {
  LayoutDashboard,
  Box,
  Tag,
  Ruler,
  FileText,
  Warehouse as WarehouseIcon,
  ClipboardList,
  ArrowRightLeft,
  Building2,
  UserPlus,
  Users,
  Settings,
  User,
  ShoppingCart,
  PackageCheck,
  Receipt,
  Coffee,
  ChefHat,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface NavItem {
  id: string;
  label: string;
  icon: LucideIcon;
}

export const NAV_ITEMS: NavItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { id: 'products', label: 'Products', icon: Box },
  { id: 'categories', label: 'Categories', icon: Tag },
  { id: 'units', label: 'Units of Measure', icon: Ruler },
  { id: 'purchaseOrders', label: 'Purchase Orders', icon: FileText },
  { id: 'receiveOrders', label: 'Receive Orders', icon: PackageCheck },
  { id: 'warehouses', label: 'Warehouses', icon: WarehouseIcon },
  { id: 'adjustments', label: 'Adjustments', icon: ClipboardList },
  { id: 'transfers', label: 'Transfers', icon: ArrowRightLeft },
  { id: 'suppliers', label: 'Suppliers', icon: Building2 },
  { id: 'customers', label: 'Customers', icon: UserPlus },
  { id: 'team', label: 'Team', icon: Users },
  { id: 'settings', label: 'Settings', icon: Settings },
  { id: 'account', label: 'Account', icon: User },
  { id: 'pos', label: 'Point of Sale', icon: ShoppingCart },
  { id: 'barPos', label: 'Bar & Restaurant', icon: Coffee },
  { id: 'kitchen', label: 'Kitchen Display', icon: ChefHat },
  { id: 'sales', label: 'Sales', icon: Receipt },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'SKU-001',
    name: 'Premium Basmati Rice',
    category: 'Grains & Cereals',
    price: 85.0,
    cost: 62.0,
    stock: 234,
    reorder: 50,
    location: 'Warehouse A',
    supplier: 'GoldGrain Ltd',
    barcode: '5901234123457',
    status: 'in_stock',
    image: '🍚',
    unit: 'kg',
    lastUpdated: '2026-02-10',
  },
  {
    id: 'SKU-002',
    name: 'Organic Palm Oil (5L)',
    category: 'Oils & Fats',
    price: 120.0,
    cost: 88.0,
    stock: 12,
    reorder: 30,
    location: 'Warehouse A',
    supplier: 'Tropica Oils',
    barcode: '5901234123458',
    status: 'low_stock',
    image: '🫒',
    unit: 'bottles',
    lastUpdated: '2026-02-09',
    expiryDate: '2026-04-15',
  },
  {
    id: 'SKU-003',
    name: 'Nestle Milo (400g)',
    category: 'Beverages',
    price: 32.5,
    cost: 24.0,
    stock: 456,
    reorder: 100,
    location: 'Store Front',
    supplier: 'Nestle Ghana',
    barcode: '5901234123459',
    status: 'in_stock',
    image: '☕',
    unit: 'tins',
    lastUpdated: '2026-02-11',
    expiryDate: '2026-03-10',
    skipKitchen: true,
    batchTracking: true,
    batches: [
      {
        id: 'BT-001',
        batchNumber: 'LOT-2026-0045',
        productId: 'SKU-003',
        quantity: 200,
        initialQuantity: 200,
        expiryDate: '2026-03-10',
        receivedDate: '2026-01-15',
        sourcePoId: 'PO-1001',
        location: 'Store Front',
        status: 'active',
      },
      {
        id: 'BT-002',
        batchNumber: 'LOT-2026-0078',
        productId: 'SKU-003',
        quantity: 256,
        initialQuantity: 256,
        expiryDate: '2026-06-20',
        receivedDate: '2026-02-03',
        sourcePoId: 'PO-1002',
        location: 'Store Front',
        status: 'active',
      },
    ],
  },
  {
    id: 'SKU-004',
    name: 'Peak Milk Powder (900g)',
    category: 'Dairy',
    price: 68.0,
    cost: 52.0,
    stock: 0,
    reorder: 25,
    location: 'Warehouse B',
    supplier: 'FrieslandCampina',
    barcode: '5901234123460',
    status: 'out_of_stock',
    image: '🥛',
    unit: 'packs',
    lastUpdated: '2026-02-08',
    expiryDate: '2026-02-10',
    skipKitchen: true,
    batchTracking: true,
    batches: [
      {
        id: 'BT-003',
        batchNumber: 'LOT-2025-0312',
        productId: 'SKU-004',
        quantity: 0,
        initialQuantity: 50,
        expiryDate: '2026-02-10',
        receivedDate: '2025-11-05',
        sourcePoId: 'PO-1004',
        location: 'Warehouse B',
        status: 'depleted',
        notes: 'All units sold or expired',
      },
    ],
  },
  {
    id: 'SKU-005',
    name: 'Golden Penny Spaghetti',
    category: 'Pasta & Noodles',
    price: 18.0,
    cost: 12.5,
    stock: 789,
    reorder: 200,
    location: 'Warehouse A',
    supplier: 'Flour Mills',
    barcode: '5901234123461',
    status: 'in_stock',
    image: '🍝',
    unit: 'packs',
    lastUpdated: '2026-02-11',
    expiryDate: '2026-12-01',
  },
  {
    id: 'SKU-006',
    name: 'Titus Sardines (125g)',
    category: 'Canned Foods',
    price: 22.0,
    cost: 16.0,
    stock: 8,
    reorder: 40,
    location: 'Store Front',
    supplier: 'GoBel Fisheries',
    barcode: '5901234123462',
    status: 'low_stock',
    image: '🐟',
    unit: 'cans',
    lastUpdated: '2026-02-10',
    expiryDate: '2026-02-28',
    batchTracking: true,
    batches: [
      {
        id: 'BT-004',
        batchNumber: 'LOT-2025-0198',
        productId: 'SKU-006',
        quantity: 0,
        initialQuantity: 30,
        expiryDate: '2026-01-15',
        receivedDate: '2025-09-20',
        sourcePoId: 'PO-1008',
        location: 'Store Front',
        status: 'depleted',
        notes: 'Batch expired and written off',
      },
      {
        id: 'BT-005',
        batchNumber: 'LOT-2026-0012',
        productId: 'SKU-006',
        quantity: 8,
        initialQuantity: 20,
        expiryDate: '2026-02-28',
        receivedDate: '2026-01-10',
        sourcePoId: 'PO-1008',
        location: 'Store Front',
        status: 'active',
      },
    ],
  },
  {
    id: 'SKU-007',
    name: 'Voltic Water (1.5L)',
    category: 'Beverages',
    price: 5.0,
    cost: 3.2,
    stock: 1200,
    reorder: 300,
    location: 'Warehouse B',
    supplier: 'Voltic GH',
    barcode: '5901234123463',
    status: 'in_stock',
    image: '💧',
    unit: 'bottles',
    lastUpdated: '2026-02-11',
    skipKitchen: true,
  },
  {
    id: 'SKU-008',
    name: 'KeyRound Soap (Pack of 6)',
    category: 'Household',
    price: 28.0,
    cost: 20.0,
    stock: 5,
    reorder: 20,
    location: 'Warehouse A',
    supplier: 'Unilever Ghana',
    barcode: '5901234123464',
    status: 'low_stock',
    image: '🧼',
    unit: 'packs',
    lastUpdated: '2026-02-07',
  },
];

export const SUPPLIERS: Supplier[] = [
  {
    id: 1,
    name: 'GoldGrain Ltd',
    contact: 'Kwame Asante',
    phone: '+233 24 123 4567',
    email: 'kwame@goldgrain.gh',
    location: 'Tema, Greater Accra',
    products: 24,
    rating: 4.8,
    status: 'active',
  },
  {
    id: 2,
    name: 'Tropica Oils',
    contact: 'Ama Mensah',
    phone: '+233 20 987 6543',
    email: 'ama@tropicaoils.gh',
    location: 'Kumasi, Ashanti',
    products: 8,
    rating: 4.2,
    status: 'active',
  },
  {
    id: 3,
    name: 'Nestle Ghana',
    contact: 'Daniel Ofori',
    phone: '+233 27 555 1234',
    email: 'daniel@nestle.gh',
    location: 'Accra, Greater Accra',
    products: 45,
    rating: 4.9,
    status: 'active',
  },
  {
    id: 4,
    name: 'FrieslandCampina',
    contact: 'Grace Boateng',
    phone: '+233 26 444 7890',
    email: 'grace@friesland.gh',
    location: 'Tema, Greater Accra',
    products: 15,
    rating: 4.5,
    status: 'active',
  },
  {
    id: 5,
    name: 'Unilever Ghana',
    contact: 'Emmanuel Tetteh',
    phone: '+233 24 333 2211',
    email: 'emmanuel@unilever.gh',
    location: 'Tema, Greater Accra',
    products: 62,
    rating: 4.7,
    status: 'active',
  },
];

export const ADJUSTMENTS: StockAdjustment[] = [
  {
    id: 'ADJ-001',
    product: 'Premium Basmati Rice',
    type: 'Damage',
    qty: -5,
    date: '2026-02-11',
    by: 'Jude A.',
    reason: 'Water damage during storage',
    status: 'approved',
  },
  {
    id: 'ADJ-002',
    product: 'Nestle Milo (400g)',
    type: 'Recount',
    qty: 12,
    date: '2026-02-10',
    by: 'Kofi M.',
    reason: 'Physical count discrepancy',
    status: 'pending',
  },
  {
    id: 'ADJ-003',
    product: 'Titus Sardines (125g)',
    type: 'Expired',
    qty: -20,
    date: '2026-02-09',
    by: 'Jude A.',
    reason: 'Batch expired Feb 2026',
    status: 'approved',
  },
  {
    id: 'ADJ-004',
    product: 'KeyRound Soap (Pack of 6)',
    type: 'Theft',
    qty: -3,
    date: '2026-02-08',
    by: 'Ama D.',
    reason: 'Shrinkage detected during audit',
    status: 'approved',
  },
  {
    id: 'ADJ-005',
    product: 'Voltic Water (1.5L)',
    type: 'Return',
    qty: 50,
    date: '2026-02-07',
    by: 'Kofi M.',
    reason: 'Customer bulk return - wrong order',
    status: 'pending',
  },
];

export const TRANSFERS: StockTransfer[] = [
  {
    id: 'TRF-001',
    product: 'Premium Basmati Rice',
    qty: 50,
    from: 'Warehouse A',
    to: 'Store Front',
    date: '2026-02-11',
    status: 'in_transit',
    by: 'Jude A.',
  },
  {
    id: 'TRF-002',
    product: 'Voltic Water (1.5L)',
    qty: 200,
    from: 'Warehouse B',
    to: 'Store Front',
    date: '2026-02-10',
    status: 'completed',
    by: 'Kofi M.',
  },
  {
    id: 'TRF-003',
    product: 'Nestle Milo (400g)',
    qty: 30,
    from: 'Store Front',
    to: 'Warehouse A',
    date: '2026-02-09',
    status: 'completed',
    by: 'Ama D.',
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'CUS-001',
    name: 'Kwame Boateng',
    phone: '+233 24 567 8901',
    email: 'kwame.b@gmail.com',
    type: 'regular',
    totalSpent: 4280,
    visits: 47,
    lastVisit: '2026-02-12',
    notes: 'Prefers bulk grain purchases. Runs a small chop bar.',
    createdAt: '2025-06-20',
    loyaltyPts: 428,
  },
  {
    id: 'CUS-002',
    name: 'Abena Owusu',
    phone: '+233 20 333 4455',
    email: 'abena.o@yahoo.com',
    type: 'wholesale',
    totalSpent: 18650,
    visits: 23,
    lastVisit: '2026-02-11',
    notes: 'Wholesale buyer for 3 retail shops in Madina. Monthly account.',
    createdAt: '2025-04-10',
    loyaltyPts: 1865,
  },
  {
    id: 'CUS-003',
    name: 'Yaw Mensah',
    phone: '+233 55 789 0123',
    email: '',
    type: 'regular',
    totalSpent: 1520,
    visits: 18,
    lastVisit: '2026-02-10',
    notes: '',
    createdAt: '2025-09-05',
    loyaltyPts: 152,
  },
  {
    id: 'CUS-004',
    name: 'Esi Adjei',
    phone: '+233 27 111 2233',
    email: 'esi.adjei@outlook.com',
    type: 'regular',
    totalSpent: 890,
    visits: 12,
    lastVisit: '2026-02-08',
    notes: 'School canteen purchases',
    createdAt: '2025-11-15',
    loyaltyPts: 89,
  },
  {
    id: 'CUS-005',
    name: 'Kofi Tetteh',
    phone: '+233 50 444 5566',
    email: 'kofi.t@company.com',
    type: 'wholesale',
    totalSpent: 32400,
    visits: 56,
    lastVisit: '2026-02-12',
    notes: 'Largest wholesale customer. Owns Tetteh Distributors. Net-15 terms.',
    createdAt: '2025-03-01',
    loyaltyPts: 3240,
  },
  {
    id: 'CUS-006',
    name: 'Adwoa Sarpong',
    phone: '+233 24 888 9900',
    email: '',
    type: 'walk-in',
    totalSpent: 245,
    visits: 4,
    lastVisit: '2026-01-28',
    notes: '',
    createdAt: '2026-01-10',
    loyaltyPts: 24,
  },
  {
    id: 'CUS-007',
    name: 'Emmanuel Frimpong',
    phone: '+233 20 222 3344',
    email: 'emmanuel.f@gmail.com',
    type: 'regular',
    totalSpent: 3150,
    visits: 35,
    lastVisit: '2026-02-09',
    notes: 'Restaurant owner. Orders cooking oils and spices regularly.',
    createdAt: '2025-07-22',
    loyaltyPts: 315,
  },
  {
    id: 'CUS-008',
    name: 'Grace Amponsah',
    phone: '+233 55 666 7788',
    email: 'grace.a@email.com',
    type: 'regular',
    totalSpent: 2680,
    visits: 29,
    lastVisit: '2026-02-11',
    notes: 'Household bulk buyer. Comes every 2 weeks.',
    createdAt: '2025-08-18',
    loyaltyPts: 268,
  },
  {
    id: 'CUS-009',
    name: 'Samuel Osei-Bonsu',
    phone: '+233 27 555 0011',
    email: '',
    type: 'wholesale',
    totalSpent: 12800,
    visits: 15,
    lastVisit: '2026-02-07',
    notes: 'Supplies to hotels in Kumasi. Quarterly bulk orders.',
    createdAt: '2025-05-30',
    loyaltyPts: 1280,
  },
  {
    id: 'CUS-010',
    name: 'Fatima Ibrahim',
    phone: '+233 24 999 1122',
    email: 'fatima.i@gmail.com',
    type: 'regular',
    totalSpent: 1890,
    visits: 22,
    lastVisit: '2026-02-06',
    notes: '',
    createdAt: '2025-10-12',
    loyaltyPts: 189,
  },
];

export const INITIAL_POS: PurchaseOrder[] = [
  {
    id: 'PO-1001',
    supplierId: 1,
    supplierName: 'GoldGrain Ltd',
    status: 'received',
    createdDate: '2026-01-20',
    expectedDate: '2026-01-28',
    receivedDate: '2026-01-27',
    location: 'Warehouse A',
    paymentTerms: 'net30',
    notes: 'Regular monthly restock',
    createdBy: 'Jude A.',
    items: [
      {
        productId: 'SKU-001',
        name: 'Premium Basmati Rice',
        qty: 100,
        unitCost: 62.0,
        receivedQty: 100,
        image: '🍚',
        unit: 'kg',
      },
    ],
  },
  {
    id: 'PO-1002',
    supplierId: 3,
    supplierName: 'Nestle Ghana',
    status: 'shipped',
    createdDate: '2026-02-03',
    expectedDate: '2026-02-12',
    receivedDate: null,
    location: 'Store Front',
    paymentTerms: 'net15',
    notes: 'Express delivery requested',
    createdBy: 'Kofi M.',
    items: [
      {
        productId: 'SKU-003',
        name: 'Nestle Milo (400g)',
        qty: 200,
        unitCost: 24.0,
        receivedQty: 0,
        image: '☕',
        unit: 'tins',
      },
    ],
  },
  {
    id: 'PO-1003',
    supplierId: 2,
    supplierName: 'Tropica Oils',
    status: 'approved',
    createdDate: '2026-02-08',
    expectedDate: '2026-02-18',
    receivedDate: null,
    location: 'Warehouse A',
    paymentTerms: 'cod',
    notes: 'Urgent - low stock alert',
    createdBy: 'Jude A.',
    items: [
      {
        productId: 'SKU-002',
        name: 'Organic Palm Oil (5L)',
        qty: 50,
        unitCost: 88.0,
        receivedQty: 0,
        image: '🫒',
        unit: 'bottles',
      },
    ],
  },
  {
    id: 'PO-1004',
    supplierId: 4,
    supplierName: 'FrieslandCampina',
    status: 'pending',
    createdDate: '2026-02-10',
    expectedDate: '2026-02-20',
    receivedDate: null,
    location: 'Warehouse B',
    paymentTerms: 'net30',
    notes: 'Restock - item currently out of stock',
    createdBy: 'Ama D.',
    items: [
      {
        productId: 'SKU-004',
        name: 'Peak Milk Powder (900g)',
        qty: 75,
        unitCost: 52.0,
        receivedQty: 0,
        image: '🥛',
        unit: 'packs',
      },
    ],
  },
  {
    id: 'PO-1005',
    supplierId: 5,
    supplierName: 'Unilever Ghana',
    status: 'draft',
    createdDate: '2026-02-11',
    expectedDate: null,
    receivedDate: null,
    location: 'Warehouse A',
    paymentTerms: 'net30',
    notes: '',
    createdBy: 'Jude A.',
    items: [
      {
        productId: 'SKU-008',
        name: 'KeyRound Soap (Pack of 6)',
        qty: 100,
        unitCost: 20.0,
        receivedQty: 0,
        image: '🧼',
        unit: 'packs',
      },
    ],
  },
  {
    id: 'PO-1006',
    supplierId: 1,
    supplierName: 'GoldGrain Ltd',
    status: 'received',
    createdDate: '2026-01-05',
    expectedDate: '2026-01-15',
    receivedDate: '2026-01-14',
    location: 'Warehouse A',
    paymentTerms: 'net30',
    notes: '',
    createdBy: 'Kofi M.',
    items: [
      {
        productId: 'SKU-001',
        name: 'Premium Basmati Rice',
        qty: 150,
        unitCost: 60.0,
        receivedQty: 148,
        image: '🍚',
        unit: 'kg',
      },
      {
        productId: 'SKU-005',
        name: 'Golden Penny Spaghetti',
        qty: 300,
        unitCost: 12.5,
        receivedQty: 300,
        image: '🍝',
        unit: 'packs',
      },
    ],
  },
  {
    id: 'PO-1007',
    supplierId: 3,
    supplierName: 'Nestle Ghana',
    status: 'cancelled',
    createdDate: '2026-01-25',
    expectedDate: '2026-02-05',
    receivedDate: null,
    location: 'Warehouse B',
    paymentTerms: 'net15',
    notes: 'Cancelled — supplier stock unavailable',
    createdBy: 'Jude A.',
    items: [
      {
        productId: 'SKU-003',
        name: 'Nestle Milo (400g)',
        qty: 500,
        unitCost: 24.0,
        receivedQty: 0,
        image: '☕',
        unit: 'tins',
      },
    ],
  },
  {
    id: 'PO-1008',
    supplierId: 2,
    supplierName: 'Tropica Oils',
    status: 'partial',
    createdDate: '2026-01-12',
    expectedDate: '2026-01-22',
    receivedDate: '2026-01-21',
    location: 'Warehouse A',
    paymentTerms: 'net30',
    notes: 'Partial delivery — remainder back-ordered',
    createdBy: 'Jude A.',
    items: [
      {
        productId: 'SKU-002',
        name: 'Organic Palm Oil (5L)',
        qty: 80,
        unitCost: 85.0,
        receivedQty: 60,
        image: '🫒',
        unit: 'bottles',
      },
    ],
  },
];

export const RECEIVE_ORDERS = [
  {
    id: 'RO-001',
    reference: 'RCV-2026-0001',
    date: '2026-02-10',
    warehouse: 'Warehouse A',
    itemCount: 3,
    totalQty: 150,
    notes: 'Monthly stock replenishment',
    status: 'completed' as const,
    createdBy: 'Jude A.',
  },
  {
    id: 'RO-002',
    reference: 'RCV-2026-0002',
    date: '2026-02-08',
    warehouse: 'Store Front',
    itemCount: 1,
    totalQty: 50,
    notes: 'Urgent restock from local supplier',
    status: 'completed' as const,
    createdBy: 'Kofi M.',
  },
  {
    id: 'RO-003',
    reference: 'RCV-2026-0003',
    date: '2026-01-25',
    warehouse: 'Warehouse B',
    itemCount: 5,
    totalQty: 320,
    notes: 'Donation from partner organization',
    status: 'completed' as const,
    createdBy: 'Abena O.',
  },
  {
    id: 'RO-004',
    reference: 'RCV-2026-0004',
    date: '2026-02-14',
    warehouse: 'Warehouse A',
    itemCount: 2,
    totalQty: 80,
    notes: 'Sample goods from new supplier',
    status: 'draft' as const,
    createdBy: 'Jude A.',
  },
];

export const WAREHOUSES: Warehouse[] = [
  {
    id: 'WH-001',
    name: 'Warehouse A',
    type: 'Main Storage',
    address: 'Plot 12, Industrial Area, Tema',
    manager: 'Kwesi Mensah',
    phone: '+233 24 555 1234',
    email: 'kwesi@shopchain.gh',
    capacity: 5000,
    zones: ['Dry Storage', 'Cold Room', 'Loading Bay', 'Returns Area'],
  },
  {
    id: 'WH-002',
    name: 'Warehouse B',
    type: 'Secondary',
    address: 'Block 5, Spintex Road, Accra',
    manager: 'Abena Osei',
    phone: '+233 20 444 5678',
    email: 'abena@shopchain.gh',
    capacity: 3000,
    zones: ['Dry Storage', 'Bulk Area', 'Staging'],
  },
  {
    id: 'WH-003',
    name: 'Store Front',
    type: 'Retail',
    address: '15 Oxford Street, Osu, Accra',
    manager: 'Kofi Mensah',
    phone: '+233 27 333 7890',
    email: 'kofi@shopchain.gh',
    capacity: 800,
    zones: ['Shelf Display', 'Back Storage', 'Checkout'],
  },
];

export const DEMO_BILLING: BillingRecord[] = [
  { id: 'inv-001', date: '2026-02-01', desc: 'Max Plan — February 2026', amount: 'GH₵ 149.00', status: 'paid' },
  { id: 'inv-002', date: '2026-01-01', desc: 'Max Plan — January 2026', amount: 'GH₵ 149.00', status: 'paid' },
  { id: 'inv-003', date: '2025-12-01', desc: 'Basic Plan — December 2025', amount: 'GH₵ 49.00', status: 'paid' },
];

export const DEMO_USAGE: UsageData = { shops: 1, branches: 2, team: 5, products: 42, transactions: 87, storageMB: 45 };

export const MOCK_USER_USAGE: Record<string, UsageData> = {
  u1: { shops: 1, branches: 2, team: 5, products: 42, transactions: 2870, storageMB: 1420 },
  u2: { shops: 2, branches: 1, team: 8, products: 310, transactions: 4200, storageMB: 980 },
  u3: { shops: 1, branches: 0, team: 1, products: 48, transactions: 185, storageMB: 62 },
  u4: { shops: 1, branches: 0, team: 3, products: 120, transactions: 0, storageMB: 210 },
  u5: { shops: 3, branches: 5, team: 22, products: 680, transactions: 9800, storageMB: 5400 },
  u6: { shops: 0, branches: 0, team: 0, products: 0, transactions: 0, storageMB: 0 },
  u7: { shops: 1, branches: 0, team: 1, products: 47, transactions: 190, storageMB: 88 },
  u8: { shops: 2, branches: 3, team: 12, products: 480, transactions: 4850, storageMB: 1680 },
};

export const DEMO_SESSIONS: Session[] = [
  { id: 's1', device: 'Chrome on Windows', location: 'Accra, Ghana', lastActive: 'Now', current: true },
  { id: 's2', device: 'Safari on iPhone', location: 'Accra, Ghana', lastActive: '2 hours ago', current: false },
  { id: 's3', device: 'Firefox on MacOS', location: 'Kumasi, Ghana', lastActive: '3 days ago', current: false },
];

export const ADMIN_DEMO_USERS: AdminUser[] = [
  {
    id: 'u1',
    name: 'Jude Appiah',
    email: 'jude@shopchain.com',
    phone: '+233 24 111 2222',
    status: 'active',
    plan: 'max',
    shops: 1,
    branches: 2,
    joined: '2025-06-15',
    lastActive: 'Just now',
    avatar: 'JA',
  },
  {
    id: 'u2',
    name: 'Akua Mensah',
    email: 'akua.m@gmail.com',
    phone: '+233 20 555 6666',
    status: 'active',
    plan: 'basic',
    shops: 2,
    branches: 1,
    joined: '2025-08-22',
    lastActive: '1 hour ago',
    avatar: 'AM',
  },
  {
    id: 'u3',
    name: 'Kweku Asamoah',
    email: 'kweku.a@outlook.com',
    phone: '+233 55 777 8888',
    status: 'active',
    plan: 'free',
    shops: 1,
    branches: 0,
    joined: '2025-10-05',
    lastActive: 'Yesterday',
    avatar: 'KA',
  },
  {
    id: 'u4',
    name: 'Esi Boateng',
    email: 'esi.b@yahoo.com',
    phone: '+233 24 333 4444',
    status: 'deactivated',
    plan: 'basic',
    shops: 1,
    branches: 0,
    joined: '2025-07-18',
    lastActive: '2 weeks ago',
    avatar: 'EB',
  },
  {
    id: 'u5',
    name: 'Kofi Owusu',
    email: 'kofi.o@gmail.com',
    phone: '+233 50 999 0000',
    status: 'active',
    plan: 'max',
    shops: 3,
    branches: 5,
    joined: '2025-05-01',
    lastActive: '3 hours ago',
    avatar: 'KO',
  },
  {
    id: 'u6',
    name: 'Ama Serwaa',
    email: 'ama.s@company.com',
    phone: '+233 27 111 3333',
    status: 'pending',
    plan: 'free',
    shops: 0,
    branches: 0,
    joined: '2026-02-10',
    lastActive: 'Never',
    avatar: 'AS',
  },
  {
    id: 'u7',
    name: 'Yaw Frimpong',
    email: 'yaw.f@gmail.com',
    phone: '+233 20 444 7777',
    status: 'active',
    plan: 'free',
    shops: 1,
    branches: 0,
    joined: '2025-12-01',
    lastActive: '5 hours ago',
    avatar: 'YF',
  },
  {
    id: 'u8',
    name: 'Adwoa Poku',
    email: 'adwoa.p@outlook.com',
    phone: '+233 55 888 2222',
    status: 'active',
    plan: 'basic',
    shops: 2,
    branches: 3,
    joined: '2025-09-14',
    lastActive: 'Today',
    avatar: 'AP',
  },
];

export const MOCK_PAYMENT_METHODS: Record<string, PaymentMethod[]> = {
  u1: [
    {
      id: 'pm1',
      type: 'momo',
      provider: 'MTN MoMo',
      last4: '2222',
      name: 'Jude Appiah',
      isDefault: true,
      added: '2025-06-15',
      status: 'active',
    },
    {
      id: 'pm2',
      type: 'card',
      provider: 'Visa',
      last4: '8841',
      name: 'Jude Appiah',
      expiry: '09/27',
      isDefault: false,
      added: '2025-08-01',
      status: 'active',
    },
  ],
  u2: [
    {
      id: 'pm3',
      type: 'momo',
      provider: 'Vodafone Cash',
      last4: '6666',
      name: 'Akua Mensah',
      isDefault: true,
      added: '2025-08-22',
      status: 'active',
    },
  ],
  u3: [],
  u4: [
    {
      id: 'pm4',
      type: 'momo',
      provider: 'MTN MoMo',
      last4: '4444',
      name: 'Esi Boateng',
      isDefault: true,
      added: '2025-07-18',
      status: 'expired',
    },
  ],
  u5: [
    {
      id: 'pm5',
      type: 'card',
      provider: 'Mastercard',
      last4: '3109',
      name: 'Kofi Owusu',
      expiry: '12/26',
      isDefault: true,
      added: '2025-05-01',
      status: 'active',
    },
    {
      id: 'pm6',
      type: 'momo',
      provider: 'AirtelTigo Money',
      last4: '0000',
      name: 'Kofi Owusu',
      isDefault: false,
      added: '2025-11-10',
      status: 'active',
    },
    {
      id: 'pm7',
      type: 'card',
      provider: 'Visa',
      last4: '5522',
      name: 'Kofi Owusu',
      expiry: '03/25',
      isDefault: false,
      added: '2025-05-01',
      status: 'expired',
    },
  ],
  u6: [],
  u7: [],
  u8: [
    {
      id: 'pm8',
      type: 'momo',
      provider: 'MTN MoMo',
      last4: '2222',
      name: 'Adwoa Poku',
      isDefault: true,
      added: '2025-09-14',
      status: 'active',
    },
  ],
};

export const MOCK_PAYMENT_HISTORY: Record<string, PaymentRecord[]> = {
  u1: [
    {
      id: 'tx1',
      date: '2026-02-01',
      amount: 120,
      plan: 'Max',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2602-A1M1',
    },
    {
      id: 'tx2',
      date: '2026-01-01',
      amount: 120,
      plan: 'Max',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2601-A1M1',
    },
    {
      id: 'tx3',
      date: '2025-12-01',
      amount: 120,
      plan: 'Max',
      method: 'Visa •8841',
      status: 'paid',
      txRef: 'TXN-2512-A1V1',
    },
    {
      id: 'tx4',
      date: '2025-11-01',
      amount: 120,
      plan: 'Max',
      method: 'Visa •8841',
      status: 'paid',
      txRef: 'TXN-2511-A1V1',
    },
    {
      id: 'tx5',
      date: '2025-10-01',
      amount: 120,
      plan: 'Max',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2510-A1M1',
    },
    {
      id: 'tx6',
      date: '2025-09-01',
      amount: 120,
      plan: 'Max',
      method: 'MTN MoMo •2222',
      status: 'refunded',
      txRef: 'TXN-2509-A1M1',
      note: 'Billing error — refunded',
    },
    {
      id: 'tx7',
      date: '2025-08-01',
      amount: 80,
      plan: 'Basic → Max',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2508-A1M1',
      note: 'Prorated upgrade',
    },
    {
      id: 'tx8',
      date: '2025-07-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2507-A1M1',
    },
  ],
  u2: [
    {
      id: 'tx9',
      date: '2026-02-01',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'paid',
      txRef: 'TXN-2602-A2V1',
    },
    {
      id: 'tx10',
      date: '2026-01-01',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'paid',
      txRef: 'TXN-2601-A2V1',
    },
    {
      id: 'tx11',
      date: '2025-12-01',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'failed',
      txRef: 'TXN-2512-A2V1',
      note: 'Insufficient funds',
    },
    {
      id: 'tx12',
      date: '2025-12-03',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'paid',
      txRef: 'TXN-2512-A2V2',
      note: 'Retry — successful',
    },
    {
      id: 'tx13',
      date: '2025-11-01',
      amount: 50,
      plan: 'Basic',
      method: 'Vodafone Cash •6666',
      status: 'paid',
      txRef: 'TXN-2511-A2V1',
    },
  ],
  u3: [],
  u4: [
    {
      id: 'tx14',
      date: '2025-11-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •4444',
      status: 'failed',
      txRef: 'TXN-2511-A4M1',
      note: 'Payment method expired',
    },
    {
      id: 'tx15',
      date: '2025-10-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •4444',
      status: 'paid',
      txRef: 'TXN-2510-A4M1',
    },
    {
      id: 'tx16',
      date: '2025-09-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •4444',
      status: 'paid',
      txRef: 'TXN-2509-A4M1',
    },
  ],
  u5: [
    {
      id: 'tx17',
      date: '2026-02-01',
      amount: 120,
      plan: 'Max',
      method: 'Mastercard •3109',
      status: 'paid',
      txRef: 'TXN-2602-A5C1',
    },
    {
      id: 'tx18',
      date: '2026-01-01',
      amount: 120,
      plan: 'Max',
      method: 'Mastercard •3109',
      status: 'paid',
      txRef: 'TXN-2601-A5C1',
    },
    {
      id: 'tx19',
      date: '2025-12-01',
      amount: 120,
      plan: 'Max',
      method: 'Mastercard •3109',
      status: 'paid',
      txRef: 'TXN-2512-A5C1',
    },
    {
      id: 'tx20',
      date: '2025-11-01',
      amount: 120,
      plan: 'Max',
      method: 'Visa •5522',
      status: 'failed',
      txRef: 'TXN-2511-A5V1',
      note: 'Card expired',
    },
    {
      id: 'tx21',
      date: '2025-11-03',
      amount: 120,
      plan: 'Max',
      method: 'Mastercard •3109',
      status: 'paid',
      txRef: 'TXN-2511-A5C1',
      note: 'Retry with new card',
    },
  ],
  u6: [],
  u7: [],
  u8: [
    {
      id: 'tx22',
      date: '2026-02-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2602-A8M1',
    },
    {
      id: 'tx23',
      date: '2026-01-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2601-A8M1',
    },
    {
      id: 'tx24',
      date: '2025-12-01',
      amount: 50,
      plan: 'Basic',
      method: 'MTN MoMo •2222',
      status: 'paid',
      txRef: 'TXN-2512-A8M1',
    },
  ],
};

export const ADMIN_DEMO_SHOPS: AdminShop[] = [
  {
    id: 'as1',
    name: "Kofi's Mini Mart",
    type: 'Retail Store',
    owner: 'Jude Appiah',
    ownerEmail: 'jude@shopchain.com',
    plan: 'max',
    branches: 2,
    team: 5,
    status: 'active',
    created: '2025-06-15',
    icon: '🏪',
  },
  {
    id: 'as2',
    name: 'Akua Fashion House',
    type: 'Retail Store',
    owner: 'Akua Mensah',
    ownerEmail: 'akua.m@gmail.com',
    plan: 'basic',
    branches: 1,
    team: 8,
    status: 'active',
    created: '2025-08-25',
    icon: '👗',
  },
  {
    id: 'as3',
    name: 'Kumasi Wholesale Hub',
    type: 'Wholesale',
    owner: 'Akua Mensah',
    ownerEmail: 'akua.m@gmail.com',
    plan: 'basic',
    branches: 0,
    team: 12,
    status: 'active',
    created: '2025-09-10',
    icon: '🏭',
  },
  {
    id: 'as4',
    name: 'Adabraka Pharmacy',
    type: 'Pharmacy',
    owner: 'Kweku Asamoah',
    ownerEmail: 'kweku.a@outlook.com',
    plan: 'free',
    branches: 0,
    team: 3,
    status: 'active',
    created: '2025-10-08',
    icon: '💊',
  },
  {
    id: 'as5',
    name: 'Osu Coffee Lounge',
    type: 'Restaurant / Bar',
    owner: 'Kofi Owusu',
    ownerEmail: 'kofi.o@gmail.com',
    plan: 'max',
    branches: 3,
    team: 10,
    status: 'active',
    created: '2025-05-05',
    icon: '☕',
  },
  {
    id: 'as6',
    name: 'Esi Electronics',
    type: 'Retail Store',
    owner: 'Esi Boateng',
    ownerEmail: 'esi.b@yahoo.com',
    plan: 'basic',
    branches: 0,
    team: 4,
    status: 'suspended',
    created: '2025-07-20',
    icon: '💻',
  },
];

// ─── Categories ───
export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-001',
    name: 'Grains & Cereals',
    icon: '🍚',
    color: '#F59E0B',
    description: 'Rice, wheat, oats, and cereal products',
    status: 'active',
  },
  {
    id: 'cat-002',
    name: 'Beverages',
    icon: '☕',
    color: '#3B82F6',
    description: 'Drinks including water, juices, sodas, and hot beverages',
    status: 'active',
  },
  {
    id: 'cat-003',
    name: 'Dairy',
    icon: '🥛',
    color: '#8B5CF6',
    description: 'Milk, cheese, yoghurt, and dairy-based products',
    status: 'active',
  },
  {
    id: 'cat-004',
    name: 'Oils & Fats',
    icon: '🫒',
    color: '#10B981',
    description: 'Cooking oils, margarine, and fat-based products',
    status: 'active',
  },
  {
    id: 'cat-005',
    name: 'Canned Foods',
    icon: '🐟',
    color: '#EF4444',
    description: 'Canned fish, vegetables, beans, and preserved foods',
    status: 'active',
  },
  {
    id: 'cat-006',
    name: 'Household',
    icon: '🧼',
    color: '#06B6D4',
    description: 'Cleaning supplies, detergents, and home essentials',
    status: 'active',
  },
  {
    id: 'cat-007',
    name: 'Pasta & Noodles',
    icon: '🍝',
    color: '#F97316',
    description: 'Spaghetti, macaroni, noodles, and instant meals',
    status: 'active',
  },
  {
    id: 'cat-008',
    name: 'Frozen Foods',
    icon: '🧊',
    color: '#6366F1',
    description: 'Frozen meats, vegetables, and ready meals',
    status: 'inactive',
  },
  {
    id: 'cat-009',
    name: 'Confectionery',
    icon: '🍬',
    color: '#EC4899',
    description: 'Sweets, chocolates, biscuits, and snack bars',
    status: 'active',
  },
  {
    id: 'cat-010',
    name: 'Snacks',
    icon: '🍪',
    color: '#D97706',
    description: 'Chips, crackers, nuts, and light bites',
    status: 'active',
  },
  {
    id: 'cat-011',
    name: 'Personal Care',
    icon: '🧴',
    color: '#14B8A6',
    description: 'Toiletries, skincare, and hygiene products',
    status: 'active',
  },
  {
    id: 'cat-012',
    name: 'Baby Products',
    icon: '🍼',
    color: '#A78BFA',
    description: 'Baby food, diapers, and infant care items',
    status: 'inactive',
  },
];

// ─── Units of Measure ───
export const INITIAL_UNITS: UnitOfMeasure[] = [
  {
    id: 'uom-001',
    name: 'Kilograms',
    abbreviation: 'kg',
    type: 'Weight',
    description: 'Standard weight measurement',
    status: 'active',
  },
  {
    id: 'uom-002',
    name: 'Bottles',
    abbreviation: 'bottles',
    type: 'Count',
    description: 'Individual bottled items',
    status: 'active',
  },
  {
    id: 'uom-003',
    name: 'Packs',
    abbreviation: 'packs',
    type: 'Count',
    description: 'Pre-packaged bundles or multipacks',
    status: 'active',
  },
  {
    id: 'uom-004',
    name: 'Tins',
    abbreviation: 'tins',
    type: 'Count',
    description: 'Tinned or canned containers',
    status: 'active',
  },
  {
    id: 'uom-005',
    name: 'Cans',
    abbreviation: 'cans',
    type: 'Count',
    description: 'Standard aluminium or steel cans',
    status: 'active',
  },
  {
    id: 'uom-006',
    name: 'Pieces',
    abbreviation: 'pcs',
    type: 'Count',
    description: 'Individual countable items',
    status: 'active',
  },
  {
    id: 'uom-007',
    name: 'Cartons',
    abbreviation: 'cartons',
    type: 'Count',
    description: 'Boxed or carton packaging',
    status: 'active',
  },
  {
    id: 'uom-008',
    name: 'Litres',
    abbreviation: 'L',
    type: 'Volume',
    description: 'Standard volume measurement for liquids',
    status: 'active',
  },
  {
    id: 'uom-009',
    name: 'Grams',
    abbreviation: 'g',
    type: 'Weight',
    description: 'Small weight measurement',
    status: 'active',
  },
];

// ─── Roles & Permissions ───
export interface Role {
  id: string;
  label: string;
  icon: string;
  color: string;
  description: string;
  access: string;
}

export const ROLES: Role[] = [
  {
    id: 'owner',
    label: 'Owner',
    icon: '👑',
    color: '#F59E0B',
    description: 'Full access including billing, shop deletion, and team management',
    access: 'Everything',
  },
  {
    id: 'general_manager',
    label: 'General Manager',
    icon: '🌐',
    color: '#0EA5E9',
    description: 'Full operational access across all branches',
    access: 'All branches: Dashboard, Products, POS, Orders, Suppliers, Warehouses, Team, Reports',
  },
  {
    id: 'manager',
    label: 'Manager',
    icon: '🔷',
    color: '#3B82F6',
    description: 'All operations except billing and shop deletion',
    access: 'Dashboard, Products, POS, Orders, Suppliers, Warehouses, Team (view), Reports',
  },
  {
    id: 'inventory_manager',
    label: 'Inventory Manager',
    icon: '📦',
    color: '#10B981',
    description: 'Full inventory control',
    access: 'Products, Categories, Units, Purchase Orders, Warehouses, Adjustments, Transfers',
  },
  {
    id: 'inventory_officer',
    label: 'Inventory Officer',
    icon: '📋',
    color: '#06B6D4',
    description: 'Day-to-day stock operations',
    access: 'Products (view/edit), Adjustments, Transfers, Receiving',
  },
  {
    id: 'bar_manager',
    label: 'Bar Manager',
    icon: '🍸',
    color: '#D946EF',
    description: 'Full bar/kitchen operations, discounts, and analysis',
    access: 'Bar & Restaurant, Kitchen Display, Till Management, Sales & Kitchen Analysis, Dashboard (partial)',
  },
  {
    id: 'waiter',
    label: 'Waiter',
    icon: '🍽️',
    color: '#F472B6',
    description: 'Bar POS, till management, serve/cancel orders',
    access: 'Bar & Restaurant, Till Management, View products',
  },
  {
    id: 'kitchen_staff',
    label: 'Kitchen Staff',
    icon: '👨‍🍳',
    color: '#FB923C',
    description: 'Kitchen Display only — accept, reject, complete orders',
    access: 'Kitchen Display only',
  },
  {
    id: 'salesperson',
    label: 'Salesperson',
    icon: '🛒',
    color: '#8B5CF6',
    description: 'POS access and customer-facing operations',
    access: 'POS, View products, Own transaction history',
  },
  {
    id: 'cashier',
    label: 'Cashier',
    icon: '💰',
    color: '#EF4444',
    description: 'POS register only',
    access: 'POS only (restricted)',
  },
  {
    id: 'accountant',
    label: 'Accountant',
    icon: '📊',
    color: '#F97316',
    description: 'Financial oversight',
    access: 'Dashboard analytics, Reports, Purchase Orders (view), Transactions',
  },
  {
    id: 'viewer',
    label: 'Viewer',
    icon: '👁️',
    color: '#6B7280',
    description: 'Read-only access across all modules',
    access: 'View everything, edit nothing',
  },
];

export interface TeamMember {
  id: string;
  name: string;
  email: string;
  phone: string;
  role: string;
  status: string;
  avatar: string;
  lastActive: string;
  joinedDate: string;
}

export const INITIAL_TEAM: TeamMember[] = [
  {
    id: 'usr-001',
    name: 'Jude Appiah',
    email: 'jude@shopchain.com',
    phone: '+233 24 111 2222',
    role: 'owner',
    status: 'active',
    avatar: 'JA',
    lastActive: 'Just now',
    joinedDate: '2025-06-15',
  },
  {
    id: 'usr-002',
    name: 'Ama Darko',
    email: 'ama.d@shopchain.com',
    phone: '+233 20 333 4444',
    role: 'manager',
    status: 'active',
    avatar: 'AD',
    lastActive: '1 hour ago',
    joinedDate: '2025-07-01',
  },
  {
    id: 'usr-003',
    name: 'Kwame Boateng',
    email: 'kwame.b@gmail.com',
    phone: '+233 55 666 7777',
    role: 'salesperson',
    status: 'active',
    avatar: 'KB',
    lastActive: '3 hours ago',
    joinedDate: '2025-08-10',
  },
  {
    id: 'usr-004',
    name: 'Efua Mensah',
    email: 'efua.m@gmail.com',
    phone: '+233 24 888 9999',
    role: 'inventory_manager',
    status: 'active',
    avatar: 'EM',
    lastActive: 'Yesterday',
    joinedDate: '2025-09-01',
  },
  {
    id: 'usr-005',
    name: 'Yaw Asante',
    email: 'yaw.a@outlook.com',
    phone: '+233 50 222 3333',
    role: 'cashier',
    status: 'pending',
    avatar: 'YA',
    lastActive: 'Never',
    joinedDate: '2026-02-10',
  },
  {
    id: 'usr-006',
    name: 'Abena Osei',
    email: 'abena.o@yahoo.com',
    phone: '+233 27 444 5555',
    role: 'inventory_officer',
    status: 'deactivated',
    avatar: 'AO',
    lastActive: '2 weeks ago',
    joinedDate: '2025-11-20',
  },
];

export const getRoleMeta = (roleId: string): Role => ROLES.find((r) => r.id === roleId) || ROLES[ROLES.length - 1]!;

export type PermissionLevel = 'full' | 'partial' | 'view' | 'none';

export type PermissionMap = Record<string, PermissionLevel>;

export const DEFAULT_PERMISSIONS: Record<string, PermissionMap> = {
  owner: {
    dash_view: 'full',
    dash_export: 'full',
    prod_view: 'full',
    prod_edit: 'full',
    prod_delete: 'full',
    prod_price: 'full',
    cat_view: 'full',
    cat_edit: 'full',
    uom_view: 'full',
    uom_edit: 'full',
    pos_sales: 'full',
    pos_discount: 'full',
    pos_void: 'full',
    pos_receipts: 'full',
    bar_access: 'full',
    bar_discount: 'full',
    kitchen_access: 'full',
    bar_analysis: 'full',
    po_view: 'full',
    po_create: 'full',
    po_approve: 'full',
    sup_view: 'full',
    sup_edit: 'full',
    wh_view: 'full',
    wh_manage: 'full',
    adj_view: 'full',
    adj_create: 'full',
    adj_approve: 'full',
    xfer_view: 'full',
    xfer_create: 'full',
    team_view: 'full',
    team_invite: 'full',
    team_roles: 'full',
    set_shop: 'full',
    set_billing: 'full',
    set_delete: 'full',
  },
  general_manager: {
    dash_view: 'full',
    dash_export: 'full',
    prod_view: 'full',
    prod_edit: 'full',
    prod_delete: 'full',
    prod_price: 'full',
    cat_view: 'full',
    cat_edit: 'full',
    uom_view: 'full',
    uom_edit: 'full',
    pos_sales: 'full',
    pos_discount: 'full',
    pos_void: 'full',
    pos_receipts: 'full',
    bar_access: 'full',
    bar_discount: 'full',
    kitchen_access: 'full',
    bar_analysis: 'full',
    po_view: 'full',
    po_create: 'full',
    po_approve: 'full',
    sup_view: 'full',
    sup_edit: 'full',
    wh_view: 'full',
    wh_manage: 'full',
    adj_view: 'full',
    adj_create: 'full',
    adj_approve: 'full',
    xfer_view: 'full',
    xfer_create: 'full',
    team_view: 'full',
    team_invite: 'full',
    team_roles: 'full',
    set_shop: 'full',
    set_billing: 'none',
    set_delete: 'none',
  },
  manager: {
    dash_view: 'full',
    dash_export: 'full',
    prod_view: 'full',
    prod_edit: 'full',
    prod_delete: 'full',
    prod_price: 'full',
    cat_view: 'full',
    cat_edit: 'full',
    uom_view: 'full',
    uom_edit: 'full',
    pos_sales: 'full',
    pos_discount: 'full',
    pos_void: 'full',
    pos_receipts: 'full',
    bar_access: 'full',
    bar_discount: 'full',
    kitchen_access: 'full',
    bar_analysis: 'full',
    po_view: 'full',
    po_create: 'full',
    po_approve: 'full',
    sup_view: 'full',
    sup_edit: 'full',
    wh_view: 'full',
    wh_manage: 'full',
    adj_view: 'full',
    adj_create: 'full',
    adj_approve: 'full',
    xfer_view: 'full',
    xfer_create: 'full',
    team_view: 'full',
    team_invite: 'partial',
    team_roles: 'none',
    set_shop: 'partial',
    set_billing: 'none',
    set_delete: 'none',
  },
  bar_manager: {
    dash_view: 'partial',
    dash_export: 'none',
    prod_view: 'view',
    prod_edit: 'none',
    prod_delete: 'none',
    prod_price: 'none',
    cat_view: 'none',
    cat_edit: 'none',
    uom_view: 'none',
    uom_edit: 'none',
    pos_sales: 'none',
    pos_discount: 'none',
    pos_void: 'none',
    pos_receipts: 'none',
    bar_access: 'full',
    bar_discount: 'full',
    kitchen_access: 'full',
    bar_analysis: 'full',
    po_view: 'none',
    po_create: 'none',
    po_approve: 'none',
    sup_view: 'none',
    sup_edit: 'none',
    wh_view: 'none',
    wh_manage: 'none',
    adj_view: 'none',
    adj_create: 'none',
    adj_approve: 'none',
    xfer_view: 'none',
    xfer_create: 'none',
    team_view: 'none',
    team_invite: 'none',
    team_roles: 'none',
    set_shop: 'none',
    set_billing: 'none',
    set_delete: 'none',
  },
  waiter: {
    dash_view: 'none',
    dash_export: 'none',
    prod_view: 'view',
    prod_edit: 'none',
    prod_delete: 'none',
    prod_price: 'none',
    cat_view: 'none',
    cat_edit: 'none',
    uom_view: 'none',
    uom_edit: 'none',
    pos_sales: 'none',
    pos_discount: 'none',
    pos_void: 'none',
    pos_receipts: 'none',
    bar_access: 'full',
    bar_discount: 'partial',
    kitchen_access: 'view',
    bar_analysis: 'none',
    po_view: 'none',
    po_create: 'none',
    po_approve: 'none',
    sup_view: 'none',
    sup_edit: 'none',
    wh_view: 'none',
    wh_manage: 'none',
    adj_view: 'none',
    adj_create: 'none',
    adj_approve: 'none',
    xfer_view: 'none',
    xfer_create: 'none',
    team_view: 'none',
    team_invite: 'none',
    team_roles: 'none',
    set_shop: 'none',
    set_billing: 'none',
    set_delete: 'none',
  },
  kitchen_staff: {
    dash_view: 'none',
    dash_export: 'none',
    prod_view: 'none',
    prod_edit: 'none',
    prod_delete: 'none',
    prod_price: 'none',
    cat_view: 'none',
    cat_edit: 'none',
    uom_view: 'none',
    uom_edit: 'none',
    pos_sales: 'none',
    pos_discount: 'none',
    pos_void: 'none',
    pos_receipts: 'none',
    bar_access: 'none',
    bar_discount: 'none',
    kitchen_access: 'full',
    bar_analysis: 'none',
    po_view: 'none',
    po_create: 'none',
    po_approve: 'none',
    sup_view: 'none',
    sup_edit: 'none',
    wh_view: 'none',
    wh_manage: 'none',
    adj_view: 'none',
    adj_create: 'none',
    adj_approve: 'none',
    xfer_view: 'none',
    xfer_create: 'none',
    team_view: 'none',
    team_invite: 'none',
    team_roles: 'none',
    set_shop: 'none',
    set_billing: 'none',
    set_delete: 'none',
  },
  inventory_manager: {
    dash_view: 'partial',
    dash_export: 'partial',
    prod_view: 'full',
    prod_edit: 'full',
    prod_delete: 'full',
    prod_price: 'full',
    cat_view: 'full',
    cat_edit: 'full',
    uom_view: 'full',
    uom_edit: 'full',
    pos_sales: 'none',
    pos_discount: 'none',
    pos_void: 'none',
    pos_receipts: 'none',
    bar_access: 'none',
    bar_discount: 'none',
    kitchen_access: 'none',
    bar_analysis: 'none',
    po_view: 'full',
    po_create: 'full',
    po_approve: 'full',
    sup_view: 'full',
    sup_edit: 'full',
    wh_view: 'full',
    wh_manage: 'full',
    adj_view: 'full',
    adj_create: 'full',
    adj_approve: 'full',
    xfer_view: 'full',
    xfer_create: 'full',
    team_view: 'none',
    team_invite: 'none',
    team_roles: 'none',
    set_shop: 'none',
    set_billing: 'none',
    set_delete: 'none',
  },
  inventory_officer: {
    dash_view: 'partial',
    dash_export: 'none',
    prod_view: 'partial',
    prod_edit: 'partial',
    prod_delete: 'none',
    prod_price: 'none',
    cat_view: 'view',
    cat_edit: 'none',
    uom_view: 'view',
    uom_edit: 'none',
    pos_sales: 'none',
    pos_discount: 'none',
    pos_void: 'none',
    pos_receipts: 'none',
    bar_access: 'none',
    bar_discount: 'none',
    kitchen_access: 'none',
    bar_analysis: 'none',
    po_view: 'view',
    po_create: 'none',
    po_approve: 'none',
    sup_view: 'view',
    sup_edit: 'none',
    wh_view: 'view',
    wh_manage: 'none',
    adj_view: 'full',
    adj_create: 'full',
    adj_approve: 'none',
    xfer_view: 'full',
    xfer_create: 'full',
    team_view: 'none',
    team_invite: 'none',
    team_roles: 'none',
    set_shop: 'none',
    set_billing: 'none',
    set_delete: 'none',
  },
  salesperson: {
    dash_view: 'none',
    dash_export: 'none',
    prod_view: 'view',
    prod_edit: 'none',
    prod_delete: 'none',
    prod_price: 'none',
    cat_view: 'none',
    cat_edit: 'none',
    uom_view: 'none',
    uom_edit: 'none',
    pos_sales: 'full',
    pos_discount: 'full',
    pos_void: 'partial',
    pos_receipts: 'partial',
    bar_access: 'full',
    bar_discount: 'partial',
    kitchen_access: 'full',
    bar_analysis: 'none',
    po_view: 'none',
    po_create: 'none',
    po_approve: 'none',
    sup_view: 'none',
    sup_edit: 'none',
    wh_view: 'none',
    wh_manage: 'none',
    adj_view: 'none',
    adj_create: 'none',
    adj_approve: 'none',
    xfer_view: 'none',
    xfer_create: 'none',
    team_view: 'none',
    team_invite: 'none',
    team_roles: 'none',
    set_shop: 'none',
    set_billing: 'none',
    set_delete: 'none',
  },
  cashier: {
    dash_view: 'none',
    dash_export: 'none',
    prod_view: 'view',
    prod_edit: 'none',
    prod_delete: 'none',
    prod_price: 'none',
    cat_view: 'none',
    cat_edit: 'none',
    uom_view: 'none',
    uom_edit: 'none',
    pos_sales: 'partial',
    pos_discount: 'none',
    pos_void: 'none',
    pos_receipts: 'none',
    bar_access: 'none',
    bar_discount: 'none',
    kitchen_access: 'none',
    bar_analysis: 'none',
    po_view: 'none',
    po_create: 'none',
    po_approve: 'none',
    sup_view: 'none',
    sup_edit: 'none',
    wh_view: 'none',
    wh_manage: 'none',
    adj_view: 'none',
    adj_create: 'none',
    adj_approve: 'none',
    xfer_view: 'none',
    xfer_create: 'none',
    team_view: 'none',
    team_invite: 'none',
    team_roles: 'none',
    set_shop: 'none',
    set_billing: 'none',
    set_delete: 'none',
  },
  accountant: {
    dash_view: 'full',
    dash_export: 'full',
    prod_view: 'view',
    prod_edit: 'none',
    prod_delete: 'none',
    prod_price: 'none',
    cat_view: 'view',
    cat_edit: 'none',
    uom_view: 'view',
    uom_edit: 'none',
    pos_sales: 'none',
    pos_discount: 'none',
    pos_void: 'none',
    pos_receipts: 'full',
    bar_access: 'none',
    bar_discount: 'none',
    kitchen_access: 'none',
    bar_analysis: 'full',
    po_view: 'view',
    po_create: 'none',
    po_approve: 'none',
    sup_view: 'view',
    sup_edit: 'none',
    wh_view: 'view',
    wh_manage: 'none',
    adj_view: 'view',
    adj_create: 'none',
    adj_approve: 'none',
    xfer_view: 'view',
    xfer_create: 'none',
    team_view: 'none',
    team_invite: 'none',
    team_roles: 'none',
    set_shop: 'none',
    set_billing: 'none',
    set_delete: 'none',
  },
  viewer: {
    dash_view: 'view',
    dash_export: 'none',
    prod_view: 'view',
    prod_edit: 'none',
    prod_delete: 'none',
    prod_price: 'none',
    cat_view: 'view',
    cat_edit: 'none',
    uom_view: 'view',
    uom_edit: 'none',
    pos_sales: 'view',
    pos_discount: 'none',
    pos_void: 'none',
    pos_receipts: 'view',
    bar_access: 'none',
    bar_discount: 'none',
    kitchen_access: 'none',
    bar_analysis: 'view',
    po_view: 'view',
    po_create: 'none',
    po_approve: 'none',
    sup_view: 'view',
    sup_edit: 'none',
    wh_view: 'view',
    wh_manage: 'none',
    adj_view: 'view',
    adj_create: 'none',
    adj_approve: 'none',
    xfer_view: 'view',
    xfer_create: 'none',
    team_view: 'view',
    team_invite: 'none',
    team_roles: 'none',
    set_shop: 'view',
    set_billing: 'none',
    set_delete: 'none',
  },
};

export interface PermModuleItem {
  key: string;
  label: string;
}

export interface PermModule {
  module: string;
  perms: PermModuleItem[];
}

export const PERM_MODULES: PermModule[] = [
  {
    module: 'Dashboard',
    perms: [
      { key: 'dash_view', label: 'View analytics' },
      { key: 'dash_export', label: 'Export reports' },
    ],
  },
  {
    module: 'Products',
    perms: [
      { key: 'prod_view', label: 'View products' },
      { key: 'prod_edit', label: 'Add / edit' },
      { key: 'prod_delete', label: 'Delete' },
      { key: 'prod_price', label: 'Manage pricing' },
    ],
  },
  {
    module: 'Categories',
    perms: [
      { key: 'cat_view', label: 'View' },
      { key: 'cat_edit', label: 'Add / edit / delete' },
    ],
  },
  {
    module: 'Units of Measure',
    perms: [
      { key: 'uom_view', label: 'View' },
      { key: 'uom_edit', label: 'Add / edit / delete' },
    ],
  },
  {
    module: 'Point of Sale',
    perms: [
      { key: 'pos_sales', label: 'Process sales' },
      { key: 'pos_discount', label: 'Apply discounts' },
      { key: 'pos_void', label: 'Void transactions' },
      { key: 'pos_receipts', label: 'View all receipts' },
    ],
  },
  {
    module: 'Bar & Kitchen',
    perms: [
      { key: 'bar_access', label: 'Bar & Restaurant POS' },
      { key: 'bar_discount', label: 'Apply bar discounts' },
      { key: 'kitchen_access', label: 'Kitchen Display' },
      { key: 'bar_analysis', label: 'Sales & Kitchen Analysis' },
    ],
  },
  {
    module: 'Purchase Orders',
    perms: [
      { key: 'po_view', label: 'View POs' },
      { key: 'po_create', label: 'Create / edit' },
      { key: 'po_approve', label: 'Approve / receive' },
    ],
  },
  {
    module: 'Suppliers',
    perms: [
      { key: 'sup_view', label: 'View suppliers' },
      { key: 'sup_edit', label: 'Add / edit / delete' },
    ],
  },
  {
    module: 'Warehouses',
    perms: [
      { key: 'wh_view', label: 'View warehouses' },
      { key: 'wh_manage', label: 'Manage locations' },
    ],
  },
  {
    module: 'Adjustments',
    perms: [
      { key: 'adj_view', label: 'View' },
      { key: 'adj_create', label: 'Create' },
      { key: 'adj_approve', label: 'Approve' },
    ],
  },
  {
    module: 'Transfers',
    perms: [
      { key: 'xfer_view', label: 'View' },
      { key: 'xfer_create', label: 'Create' },
    ],
  },
  {
    module: 'Team',
    perms: [
      { key: 'team_view', label: 'View members' },
      { key: 'team_invite', label: 'Invite / remove' },
      { key: 'team_roles', label: 'Change roles' },
    ],
  },
  {
    module: 'Settings',
    perms: [
      { key: 'set_shop', label: 'Shop settings' },
      { key: 'set_billing', label: 'Billing' },
      { key: 'set_delete', label: 'Delete shop' },
    ],
  },
];

export const DISCOUNT_ROLE_LIMITS: Record<string, number> = {
  owner: 100,
  general_manager: 100,
  manager: 25,
  bar_manager: 25,
  waiter: 5,
  kitchen_staff: 0,
  inventory_manager: 0,
  inventory_officer: 0,
  salesperson: 10,
  cashier: 0,
  accountant: 0,
  viewer: 0,
};

export const NAV_PERM_MAP: Record<string, string> = {
  dashboard: 'dash_view',
  products: 'prod_view',
  categories: 'cat_view',
  units: 'uom_view',
  purchaseOrders: 'po_view',
  receiveOrders: 'po_view',
  warehouses: 'wh_view',
  adjustments: 'adj_view',
  transfers: 'xfer_view',
  suppliers: 'sup_view',
  team: 'team_view',
  pos: 'pos_sales',
  barPos: 'bar_access',
  kitchen: 'kitchen_access',
  tillManagement: 'bar_access',
  sales: 'pos_receipts',
  salesAnalysis: 'bar_analysis',
  settings: 'set_shop',
};

export const INITIAL_SALES: SaleRecord[] = [
  {
    id: 'TXN-20260215-0041',
    date: new Date(Date.now() - 3600000).toISOString(),
    items: [
      { id: 'SKU-001', name: 'Premium Basmati Rice', qty: 2, price: 85.0 },
      { id: 'SKU-003', name: 'Nestle Milo (400g)', qty: 3, price: 32.5 },
    ],
    itemCount: 5,
    subtotal: 267.5,
    tax: 33.44,
    discount: 0,
    total: 300.94,
    paymentMethod: 'cash',
    payLabel: 'Cash',
    cashier: 'Ama K.',
    customerId: 'CUS-001',
    customerName: 'Kwame Boateng',
    customerPhone: '+233 24 567 8901',
    amountTendered: 310,
    change: 9.06,
    status: 'completed',
    verifyToken: 'Xk9mQ2wRp4nB',
  },
  {
    id: 'TXN-20260215-0037',
    date: new Date(Date.now() - 7200000).toISOString(),
    items: [{ id: 'SKU-007', name: 'Voltic Water (1.5L)', qty: 10, price: 5.0 }],
    itemCount: 10,
    subtotal: 50.0,
    tax: 6.25,
    discount: 0,
    total: 56.25,
    paymentMethod: 'momo',
    payLabel: 'MTN MoMo',
    cashier: 'Ama K.',
    customerId: null,
    customerName: 'Walk-in',
    customerPhone: null,
    momoProvider: 'mtn',
    momoPhone: '024 555 6677',
    momoRef: 'MOMO-9923847',
    status: 'completed',
    verifyToken: 'vL3hTj7Ks8Yf',
  },
  {
    id: 'TXN-20260214-0028',
    date: new Date(Date.now() - 86400000 - 3600000).toISOString(),
    items: [
      { id: 'SKU-002', name: 'Organic Palm Oil (5L)', qty: 1, price: 120.0 },
      { id: 'SKU-005', name: 'Golden Penny Spaghetti', qty: 5, price: 18.0 },
      { id: 'SKU-006', name: 'Titus Sardines (125g)', qty: 4, price: 22.0 },
    ],
    itemCount: 10,
    subtotal: 298.0,
    tax: 37.25,
    discount: 14.9,
    discountType: 'percent',
    discountInput: 5,
    total: 320.35,
    paymentMethod: 'card',
    payLabel: 'Visa',
    cashier: 'Kwame B.',
    customerId: 'CUS-002',
    customerName: 'Abena Owusu',
    customerPhone: '+233 20 333 4455',
    cardType: 'Visa',
    cardTransNo: 'TXN-884201',
    status: 'completed',
    verifyToken: 'bN5cW1xDr9Gz',
  },
  {
    id: 'TXN-20260214-0019',
    date: new Date(Date.now() - 86400000 - 7200000).toISOString(),
    items: [
      { id: 'SKU-008', name: 'Nkulenu Palm Cream (800g)', qty: 2, price: 28.0 },
      { id: 'SKU-001', name: 'Premium Basmati Rice', qty: 1, price: 85.0 },
    ],
    itemCount: 3,
    subtotal: 141.0,
    tax: 17.63,
    discount: 0,
    total: 158.63,
    paymentMethod: 'cash',
    payLabel: 'Cash',
    cashier: 'Ama K.',
    customerId: 'CUS-007',
    customerName: 'Emmanuel Frimpong',
    customerPhone: '+233 20 222 3344',
    amountTendered: 160,
    change: 1.37,
    status: 'completed',
    verifyToken: 'mP8aFq4Jv2Hn',
  },
  {
    id: 'TXN-20260213-0055',
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    items: [
      { id: 'SKU-003', name: 'Nestle Milo (400g)', qty: 10, price: 32.5 },
      { id: 'SKU-007', name: 'Voltic Water (1.5L)', qty: 24, price: 5.0 },
    ],
    itemCount: 34,
    subtotal: 445.0,
    tax: 55.63,
    discount: 44.5,
    discountType: 'percent',
    discountInput: 10,
    total: 456.13,
    paymentMethod: 'momo',
    payLabel: 'MTN MoMo',
    cashier: 'Kwame B.',
    customerId: 'CUS-005',
    customerName: 'Kofi Tetteh',
    customerPhone: '+233 50 444 5566',
    momoProvider: 'mtn',
    momoPhone: '050 444 5566',
    momoRef: 'MOMO-7712049',
    status: 'completed',
    verifyToken: 'dR6tYn3Lk7Ws',
  },
  {
    id: 'TXN-20260212-0044',
    date: new Date(Date.now() - 3 * 86400000).toISOString(),
    items: [{ id: 'SKU-005', name: 'Golden Penny Spaghetti', qty: 20, price: 18.0 }],
    itemCount: 20,
    subtotal: 360.0,
    tax: 45.0,
    discount: 0,
    total: 405.0,
    paymentMethod: 'cash',
    payLabel: 'Cash',
    cashier: 'Ama K.',
    customerId: 'CUS-009',
    customerName: 'Samuel Osei-Bonsu',
    customerPhone: '+233 27 555 0011',
    amountTendered: 405,
    change: 0,
    status: 'reversed',
    reversedAt: '2026-02-12T11:30:00.000Z',
    reversedBy: 'manager',
    reversalReason: 'Customer returned — wrong product ordered',
    verifyToken: 'gH2eAm5Ux8Rc',
  },
  {
    id: 'TXN-20260211-0032',
    date: new Date(Date.now() - 3 * 86400000 - 3600000).toISOString(),
    items: [
      { id: 'SKU-001', name: 'Premium Basmati Rice', qty: 3, price: 85.0 },
      { id: 'SKU-002', name: 'Organic Palm Oil (5L)', qty: 2, price: 120.0 },
    ],
    itemCount: 5,
    subtotal: 495.0,
    tax: 61.88,
    discount: 0,
    total: 556.88,
    paymentMethod: 'split',
    payLabel: 'Split (2)',
    cashier: 'Ama K.',
    customerId: 'CUS-008',
    customerName: 'Grace Amponsah',
    customerPhone: '+233 55 666 7788',
    splits: [
      { method: 'cash', label: 'Cash', amount: 300.0, detail: 'Tendered: GH\u20B5 300.00' },
      {
        method: 'momo',
        label: 'MTN MoMo',
        amount: 256.88,
        detail: 'MTN MoMo \u00B7 055 666 7788 \u00B7 Ref: MOMO-5504821',
      },
    ],
    status: 'completed',
    verifyToken: 'qJ4zVb6Ce9Tw',
  },
  {
    id: 'TXN-20260210-0018',
    date: new Date(Date.now() - 4 * 86400000).toISOString(),
    items: [{ id: 'SKU-006', name: 'Titus Sardines (125g)', qty: 6, price: 22.0 }],
    itemCount: 6,
    subtotal: 132.0,
    tax: 16.5,
    discount: 0,
    total: 148.5,
    paymentMethod: 'momo',
    payLabel: 'TCash',
    cashier: 'Kwame B.',
    customerId: null,
    customerName: 'Walk-in',
    customerPhone: null,
    momoProvider: 'tcash',
    momoPhone: '027 888 9900',
    momoRef: 'TC-3301122',
    status: 'pending_reversal',
    reversalReason: 'Suspected pricing error',
    reversalRequestedBy: 'salesperson',
    reversalRequestedAt: '2026-02-10T12:00:00.000Z',
    verifyToken: 'wE7iOp1Sn3Yd',
  },
  {
    id: 'TXN-20260209-0063',
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    items: [
      { id: 'SKU-003', name: 'Nestle Milo (400g)', qty: 2, price: 32.5 },
      { id: 'SKU-007', name: 'Voltic Water (1.5L)', qty: 6, price: 5.0 },
      { id: 'SKU-008', name: 'Nkulenu Palm Cream (800g)', qty: 1, price: 28.0 },
    ],
    itemCount: 9,
    subtotal: 123.0,
    tax: 15.38,
    discount: 6.15,
    discountType: 'percent',
    discountInput: 5,
    total: 132.23,
    paymentMethod: 'card',
    payLabel: 'Mastercard',
    cashier: 'Ama K.',
    customerId: 'CUS-003',
    customerName: 'Yaw Mensah',
    customerPhone: '+233 55 789 0123',
    cardType: 'Mastercard',
    cardTransNo: 'TXN-556099',
    status: 'completed',
    verifyToken: 'fK8uZl2Xh5Mn',
  },
  {
    id: 'TXN-20260208-0011',
    date: new Date(Date.now() - 6 * 86400000).toISOString(),
    items: [
      { id: 'SKU-001', name: 'Premium Basmati Rice', qty: 5, price: 85.0 },
      { id: 'SKU-005', name: 'Golden Penny Spaghetti', qty: 10, price: 18.0 },
      { id: 'SKU-003', name: 'Nestle Milo (400g)', qty: 5, price: 32.5 },
      { id: 'SKU-007', name: 'Voltic Water (1.5L)', qty: 12, price: 5.0 },
    ],
    itemCount: 32,
    subtotal: 827.5,
    tax: 103.44,
    discount: 82.75,
    discountType: 'percent',
    discountInput: 10,
    total: 848.19,
    paymentMethod: 'cash',
    payLabel: 'Cash',
    cashier: 'Kwame B.',
    customerId: 'CUS-005',
    customerName: 'Kofi Tetteh',
    customerPhone: '+233 50 444 5566',
    amountTendered: 850,
    change: 1.81,
    status: 'completed',
    verifyToken: 'tA9rGd4Pj6Qc',
  },
];
