import type { PlanTier, PlanId, PlanLimits } from '@/types';

export const PLAN_TIERS: Record<PlanId, PlanTier> = {
  free: {
    id: 'free',
    name: 'Free',
    icon: '🆓',
    color: '#6B7280',
    price: 0,
    badge: 'Free',
    limits: {
      shops: 1,
      branchesPerShop: 0,
      teamPerShop: 3,
      productsPerShop: 50,
      monthlyTransactions: 200,
      storageMB: 100,
      suppliers: 5,
      warehouses: 0,
    },
    features: {
      pos: 'basic',
      receipts: 'name_only',
      reports: 'basic',
      barcode: false,
      purchaseOrders: 'view',
      stockTransfers: false,
      lowStockAlerts: false,
      twoFA: false,
      apiAccess: false,
      dataExport: false,
      customBranding: false,
      auditTrail: 0,
      generalManager: false,
      support: 'community',
    },
  },
  basic: {
    id: 'basic',
    name: 'Basic',
    icon: '💙',
    color: '#3B82F6',
    price: 49,
    badge: 'Basic',
    limits: {
      shops: 3,
      branchesPerShop: 3,
      teamPerShop: 15,
      productsPerShop: 500,
      monthlyTransactions: 5000,
      storageMB: 2048,
      suppliers: 50,
      warehouses: 1,
    },
    features: {
      pos: 'full',
      receipts: 'logo_footer',
      reports: 'advanced_csv',
      barcode: true,
      purchaseOrders: 'full',
      stockTransfers: 'branches',
      lowStockAlerts: 'email',
      twoFA: true,
      apiAccess: false,
      dataExport: 'csv',
      customBranding: false,
      auditTrail: 30,
      generalManager: false,
      support: 'email_48h',
    },
  },
  max: {
    id: 'max',
    name: 'Max',
    icon: '💎',
    color: '#8B5CF6',
    price: 149,
    badge: 'Max',
    limits: {
      shops: -1,
      branchesPerShop: -1,
      teamPerShop: -1,
      productsPerShop: -1,
      monthlyTransactions: -1,
      storageMB: 20480,
      suppliers: -1,
      warehouses: -1,
    },
    features: {
      pos: 'full_split',
      receipts: 'full_thermal',
      reports: 'advanced_all',
      barcode: true,
      purchaseOrders: 'auto_reorder',
      stockTransfers: 'full',
      lowStockAlerts: 'all',
      twoFA: true,
      apiAccess: true,
      dataExport: 'all',
      customBranding: true,
      auditTrail: 365,
      generalManager: true,
      support: 'whatsapp_4h',
    },
  },
};

export const PLAN_ORDER: PlanId[] = ['free', 'basic', 'max'];
export const TRIAL_DAYS = 14;

export const PLAN_FEATURES_TABLE: Array<{ label: string; key: keyof PlanLimits; format: (v: number) => string }> = [
  { label: 'Shops', key: 'shops', format: (v) => (v === -1 ? 'Unlimited' : String(v)) },
  {
    label: 'Branches / Shop',
    key: 'branchesPerShop',
    format: (v) => (v === -1 ? 'Unlimited' : v === 0 ? 'None' : `Up to ${v}`),
  },
  { label: 'Team Members / Shop', key: 'teamPerShop', format: (v) => (v === -1 ? 'Unlimited' : String(v)) },
  { label: 'Products / Shop', key: 'productsPerShop', format: (v) => (v === -1 ? 'Unlimited' : String(v)) },
  {
    label: 'Monthly Transactions',
    key: 'monthlyTransactions',
    format: (v) => (v === -1 ? 'Unlimited' : v.toLocaleString()),
  },
  { label: 'Storage', key: 'storageMB', format: (v) => (v >= 1024 ? `${v / 1024} GB` : `${v} MB`) },
  { label: 'Suppliers', key: 'suppliers', format: (v) => (v === -1 ? 'Unlimited' : `Up to ${v}`) },
  { label: 'Warehouses', key: 'warehouses', format: (v) => (v === -1 ? 'Unlimited' : v === 0 ? '—' : String(v)) },
];
